project:
  type: book
  pre-render: "python build_glossary_from_book.py"
  execute-dir: project
  output-dir: docs

editor:
  render-on-save: true

lang: de
execute: 
  enabled: true
  eval: false

filters:
  - filters/gloss.lua
  - filters/collapsable.lua


book:
  title: "Hands-On Computer Science"
  author: "Nicolas Meseth"
  cover-image: cover.png
  date: today
  date-format: long
  search: true
  output-file: "Hands-On-Computer-Science-Book"
  #downloads: [pdf]
  
  chapters:
    - index.qmd
    - preparation.qmd

    - colors.qmd
    - numbers.qmd
    - text.qmd
    #- images.qmd
    #- sound.qmd
    #- codes.qmd
    #- conversion.qmd
    #- information.qmd
    #- sensors.qmd
    #- signals.qmd
    #- protocols.qmd
    #- encryption.qmd
    #- algorithms.qmd
    #- compression.qmd
    #- computer.qmd
    #- problems.qmd

    - glossary.qmd
    - references.qmd

bibliography: references.bib
nocite: |
  @*

format:
  html:
    theme: cosmo
    highlight: pygments
    toc-depth: 3
    number-sections: true
    code-annotations: hover
    code-line-numbers: true
    include-in-header: partials/datatables.html
    include-after-body: partials/collapsable.html
    css: 
      - partials/gloss.css
      - partials/collapsable.css

  #pdf:
  #  documentclass: scrreprt
  #  include-in-header: 
  #    text: |
  #      \usepackage{makeidx}
  #      \makeindex
  #  include-after-body: 
  #    text: |
  #      \printindex
  #docx:
  #  toc: true
  #  number-sections: true
  #  highlight-style: github