project:
  type: book
  #pre-render: "python build_glossary_from_book.py"
  execute-dir: project
  output-dir: docs

editor:
  render-on-save: true

lang: de
execute: 
  enabled: true
  eval: false
  freeze: false

filters:
  - filters/gloss.lua
  - filters/collapsable.lua


book:
  title: "Hands-On Computer Science"
  author: "Nicolas Meseth"
  description: "Ein Online-Buch mit Experimenten, die Schritt für Schritt in die Welt der Digitalisierung, Programmierung und Künstliche Intelligenz einführen."
  cover-image: cover.jpg
  date: today
  date-format: long
  search: true
  output-file: "Hands-On-Computer-Science-Book"
  #downloads: [pdf]
  
  chapters:
    - index.qmd
    - preparation.qmd

    - part: "Digitalisierung"
      chapters:
        - part-1-dap/colors.qmd
        - part-1-dap/numbers.qmd
        - part-1-dap/text.qmd
        - part-1-dap/images.qmd
        #- part-1-dap/sound.qmd
        - part-1-dap/sensors.qmd
        #- codes.qmd
        #- conversion.qmd
        #- information.qmd
        #- sensors.qmd
        #- signals.qmd
        #- protocols.qmd
        #- encryption.qmd
        #- algorithms.qmd
        #- compression.qmd
        #- computer.qmd
        #- problems.qmd

    - part: "Künstliche Intelligenz"
      chapters:
        - part-2-ai/learning.qmd
        - part-2-ai/probabilities.qmd
        - part-2-ai/embeddings.qmd
        - part-2-ai/tools.qmd
        - part-2-ai/tokens.qmd
        - part-2-ai/training.qmd
        - part-2-ai/rewards.qmd
        
        #- part-2-ai/listen.qmd
        #- part-2-ai/speaking.qmd
        #- part-2-ai/language.qmd
        #- part-2-ai/vision.qmd

    #- glossary.qmd
    - references.qmd

bibliography: references.bib
nocite: |
  @*

format:
  html:
    page-layout: article
    grid:
      margin-width: 300px
    theme: cosmo
    highlight: pygments
    toc: true
    toc-location: right
    toc-depth: 3
    number-sections: true
    code-annotations: hover
    code-line-numbers: true
    include-in-header: partials/datatables.html
    include-after-body: partials/collapsable.html
    css: 
      - partials/gloss.css
      - partials/collapsable.css

  pdf:
   documentclass: scrreprt
   include-in-header: 
     text: |
       \usepackage{makeidx}
       \makeindex
   include-after-body: 
     text: |
       \printindex
  # docx:
  #  toc: true
  #  number-sections: true
  #  highlight-style: github