# Glossar {.unnumbered}

::: {#glossar-table .datatable data-order='[[0,"asc"]]' }
| Begriff | Kategorie | Definition | Kapitel |
|---|---|---|---|
| <span id="gl-additive-farbmischung">Additive Farbmischung</span> | Physik | Mischen von Farben durch Hinzufügen von Licht | @sec-colors |
| <span id="gl-argument">Argument</span> | Programmierung | Platzhalter für übergebene Werte einer Funktion | @sec-colors |
| <span id="gl-ascii-code">ASCII-Code</span> | Codesysteme | Ein standardisiertes Kodierungssystem für Texte, das jedem Zeichen eine eindeutige Bitfolge zuweist. | @sec-text |
| <span id="gl-bedingung">Bedingung</span> | Programmierung | Aussage, die wahr oder falsch sein kann und die Ausführung von Code steuert | @sec-colors |
| <span id="gl-bibliothek">Bibliothek</span> | Programmierung | Eine Bündelung von fertigen Funktionen, Klassen oder Konstanten in einer Programmiersprache | @sec-colors |
| <span id="gl-binary-digit">Binary Digit</span> | Zahlensysteme | Eine einzelne Binärziffer, also eine 0 oder eine 1 | @sec-numbers |
| <span id="gl-binar">Binär</span> | Zahlensysteme | Lateinisch für "zu zweit" oder "paarweise". | @sec-numbers |
| <span id="gl-binarsystem">Binärsystem</span> | Zahlensysteme | Ein Zahlensystem, das nur die Ziffern 0 und 1 verwendet. | @sec-numbers |
| <span id="gl-binarziffer">Binärziffer</span> | Zahlensysteme | Eine einzelne Ziffer im Binärsystem, also eine 0 oder eine 1 | @sec-numbers |
| <span id="gl-bit">Bit</span> | Bits & Bytes | Kurzform für "Binary Digit"; kleinste Informationseinheit | @sec-numbers |
| <span id="gl-boilerplate-code">Boilerplate-Code</span> | Programmierung | Vorlagen-Code, der häufig wiederverwendet wird und oft unverändert bleibt. | @sec-colors |
| <span id="gl-brick-viewer">Brick Viewer</span> | Hardware | Ein Werkzeug zum schnellen Testen der Tinkerforge-Bauteile | @sec-colors |
| <span id="gl-bug">Bug</span> | Programmierung | Ein Fehler in einem Programm, der dazu führt, dass es nicht wie erwartet funktioniert. | @sec-text |
| <span id="gl-byte">Byte</span> | Bits & Bytes | Eine Gruppe von 8 Bits | @sec-numbers |
| <span id="gl-cmyk">CMYK</span> | Hardware | Abkürzung der Grundfarben im Farbdruck | @sec-colors |
| <span id="gl-codeblock">Codeblock</span> | Programmierung | Ein zusammenhängender Abschnitt von Programmcode, der eine bestimmte Aufgabe erfüllt. In Python sind Codeblöcke durch Einrückungen definiert. | @sec-numbers |
| <span id="gl-codepage">Codepage</span> | Codesysteme | Eine Erweiterung eines Kodierungssystems, die zusätzliche Zeichen definiert. | @sec-text |
| <span id="gl-codepunkt">Codepunkt</span> | Codesysteme | Eine eindeutige Nummer, die einem Zeichen in einem Zeichensatz zugeordnet ist. | @sec-text |
| <span id="gl-datentyp">Datentyp</span> | Programmierung | Ein Format, das angibt, welche Art von Daten in einer Variablen gespeichert werden kann. | @sec-numbers |
| <span id="gl-dekodieren">Dekodieren</span> | Codesysteme | Das Umwandeln von kodierten Informationen zurück in ihr ursprüngliches Format. | @sec-text |
| <span id="gl-dezimalsystem">Dezimalsystem</span> | Zahlensysteme | Ein Zahlensystem, das die Ziffern 0 bis 9 verwendet. | @sec-numbers |
| <span id="gl-dictionary">Dictionary</span> | Programmierung | Eine Sammlung von Schlüssel-Wert-Paaren, die eine schneller Suche ermöglichen. | @sec-text |
| <span id="gl-drehknopf">Drehknopf</span> | Hardware | Ein drehbarer Button mit Zählerfunktion. | @sec-numbers |
| <span id="gl-dry-prinzip">DRY-Prinzip</span> | Programmierung | Grundprinzip in der Programmierung, Code möglichst nicht zu wiederholen. | @sec-numbers |
| <span id="gl-dualsystem">Dualsystem</span> | Zahlensyteme | s. Binärsystem | @sec-numbers |
| <span id="gl-elektromagnetische-strahlung">Elektromagnetische Strahlung</span> | Physik | Form von Energie, die sich in Wellen durch den Raum bewegt | @sec-colors |
| <span id="gl-else-anweisung">Else-Anweisung</span> | Programmieren | Ein optionaler Teil einer if-Anweisung, der ausgeführt wird, wenn keine der vorherigen Bedingungen zutrifft. | @sec-text |
| <span id="gl-endlosschleife">Endlosschleife</span> | Programmierung | Eine Schleife in einem Programm, die ewig läuft. | @sec-numbers |
| <span id="gl-eva-schema">EVA-Schema</span> | Programmierung | Ein Modell zur Repräsentation von Problemen anhand von Eingaben, Verarbeitungen und Ausgaben | @sec-numbers |
| <span id="gl-for-schleife">For-Schleife</span> | Programmierung | Wiederholung mit Zähler, s. Zählerschleife | @sec-colors |
| <span id="gl-frequenz">Frequenz</span> | Physik | Wie oft etwas pro Sekunde passiert | @sec-colors |
| <span id="gl-funktion">Funktion</span> | Programmierung | Benannter Codeblock zur Lösung eines definierten Problems. | @sec-numbers |
| <span id="gl-gigabyte">Gigabyte</span> | Bits & Bytes | 1.000.000.000 Bytes | @sec-numbers |
| <span id="gl-hertz-hz">Hertz (Hz)</span> | Physik | Einheit für Frequenz (1/s) | @sec-colors |
| <span id="gl-hsv-modell">HSV-Modell</span> | Codesysteme | Farbmodell, das Farben durch Farbton, Sättigung und Helligkeit beschreibt | @sec-colors |
| <span id="gl-hue-farbkreis">Hue-Farbkreis</span> | Codesysteme | Kreis, der Farben nach ihrem Farbton anordnet | @sec-colors |
| <span id="gl-infrarot-abstandssensor">Infrarot-Abstandssensor</span> | Hardware | Ein Sensor, der über Licht des Infrarotspektrums Abstände messen kann. | @sec-text |
| <span id="gl-instanz">Instanz</span> | Programmierung | Ein erzeugtes Objekt einer Klasse, die die definierten Eigenschaften und Funktionen nutzen kann | @sec-colors |
| <span id="gl-keyboard">Keyboard</span> | Hardware | Tastatur | @sec-text |
| <span id="gl-kilobyte">Kilobyte</span> | Bits & Bytes | 1.000 Bytes | @sec-numbers |
| <span id="gl-klasse">Klasse</span> | Programmierung | Baupläne für Objekte, die bestimmte Eigenschaften und Funktionen definieren | @sec-colors |
| <span id="gl-kodieren">Kodieren</span> | Codesysteme | Das Umwandeln von Informationen in ein bestimmtes Format, das von einem Computer verarbeitet werden kann. | @sec-text |
| <span id="gl-kommandzeile">Kommandzeile</span> | Programmierung | Der Bereich, in dem Befehle eingegeben und ausgegeben werden. | @sec-numbers |
| <span id="gl-konstante">Konstante</span> | Programmierung | Ein Wert, der sich während der Programmausführung nicht ändert. | @sec-numbers |
| <span id="gl-kontrollstruktur">Kontrollstruktur</span> | Programmierung | Eine Struktur, die den Fluss eines Programms steuert. | @sec-numbers |
| <span id="gl-led">LED</span> | Hardware | Steht für *light emitting diode* | @sec-colors |
| <span id="gl-megabyte">Megabyte</span> | Bits & Bytes | 1.000.000 Bytes | @sec-numbers |
| <span id="gl-methode">Methode</span> | Programmierung | Funktion, die zu einem Objekt gehört | @sec-colors |
| <span id="gl-objekt">Objekt</span> | Programmierung | Eine konkrete Instanz einer Klasse, die die definierten Eigenschaften und Funktionen nutzen kann. | @sec-colors |
| <span id="gl-oktalsystem">Oktalsystem</span> | Zahlensysteme | Ein Zahlensystem, das die Ziffern 0 bis 7 verwendet. | @sec-numbers |
| <span id="gl-parameter">Parameter</span> | Programmierung | Werte, die an eine Funktion übergeben werden | @sec-colors, @sec-numbers |
| <span id="gl-programm">Programm</span> | Programmierung | Abfolge von Anweisungen, die ein Computer ausführt | @sec-colors |
| <span id="gl-programmabsturz">Programmabsturz</span> | Programmierung | Ein unerwartetes Beenden eines Programms | @sec-numbers |
| <span id="gl-rgb-led">RGB LED</span> | Hardware | Eine LED, die in verschiedenen Farben leuchten kann. | @sec-colors |
| <span id="gl-rgb-farbkodierung">RGB-Farbkodierung</span> | Codesysteme | Kodierung von Farben mittels Rot-, Grün- und Blauwerten | @sec-colors |
| <span id="gl-schleife">Schleife</span> | Programmierung | Wiederholung von Programmcode | @sec-colors |
| <span id="gl-schlusselwort">Schlüsselwort</span> | Programmierung | Begriff, der in der Programmiersprache eine feste Bedeutung hat | @sec-colors |
| <span id="gl-stellenwertsystem">Stellenwertsystem</span> | Zahlensysteme | Ein System, bei dem der Wert einer Ziffer von ihrer Position abhängt. | @sec-numbers |
| <span id="gl-subtraktive-farbmischung">Subtraktive Farbmischung</span> | Physik | Mischen von Farben durch Entfernen von Licht | @sec-colors |
| <span id="gl-textdatei">Textdatei</span> | Codesysteme | Eine Datei, die nur Textinformationen enthält und keine Formatierungen oder Binärdaten. | @sec-text |
| <span id="gl-uid">UID</span> | Programmierung | *Unique Identifier*: Eindeutige Identifikation, hier eines Tinkerforge-Geräts. | @sec-colors |
| <span id="gl-unicode">Unicode</span> | Codesysteme | Ein internationaler Standard zur Kodierung von Texten, der eine große Anzahl von Zeichen aus verschiedenen Schriftsystemen umfasst. | @sec-text |
| <span id="gl-utf-8">UTF-8</span> | Codesysteme | Eine Kodierungsmethode für Unicode-Zeichen, die variable Byte-Längen verwendet. | @sec-text |
| <span id="gl-verschachtelte-kontrollstruktur">Verschachtelte Kontrollstruktur</span> | Programmierung | Ein if-Statement, das innerhalb eines anderen if-Statements steht. | @sec-numbers |
| <span id="gl-wellenlange">Wellenlänge</span> | Physik | der Abstand zwischen zwei aufeinanderfolgenden Wellen | @sec-colors |
| <span id="gl-while-schleife">While-Schleife</span> | Programmierung | Wiederholung von Programmcode, solange eine Bedingung erfüllt ist | @sec-colors |
| <span id="gl-zeichenkette">Zeichenkette</span> | Programmierung | Eine Abfolge von Zeichen | @sec-text |
| <span id="gl-zahlerschleife">Zählerschleife</span> | Programmierung | Wiederholung mit Zähler | @sec-colors |
:::

