<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; Farben 🌈 – Hands-On Computer Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./numbers.html" rel="next">
<link href="./prerequisites.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-364982630eef5352dd1537128a8ed5cb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./colors.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Farben 🌈</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Hands-On Computer Science</a> 
        <div class="sidebar-tools-main">
    <a href="./Hands-On-Computer-Science-Book.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimente</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prerequisites.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Voraussetzungen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./colors.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Farben 🌈</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Zahlen 🔢</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./text.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Texte</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./images.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bilder</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./codes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Codes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conversion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Umwandlung</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./information.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Information</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sensoren</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./signals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Signale</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./protocols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Protokolle</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./encryption.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Verschlüsselung</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./algorithms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Algorithmen</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./compression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Kompression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./computer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Computer</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Probleme</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literaturverzeichnis</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#lernziele" id="toc-lernziele" class="nav-link active" data-scroll-target="#lernziele">Lernziele</a></li>
  <li><a href="#experimentaufbau" id="toc-experimentaufbau" class="nav-link" data-scroll-target="#experimentaufbau">Experimentaufbau</a></li>
  <li><a href="#erste-schritte-mit-der-led" id="toc-erste-schritte-mit-der-led" class="nav-link" data-scroll-target="#erste-schritte-mit-der-led"><span class="header-section-number">1.1</span> Erste Schritte mit der LED</a></li>
  <li><a href="#unser-erstes-programm" id="toc-unser-erstes-programm" class="nav-link" data-scroll-target="#unser-erstes-programm"><span class="header-section-number">1.2</span> Unser erstes Programm</a>
  <ul class="collapse">
  <li><a href="#programme" id="toc-programme" class="nav-link" data-scroll-target="#programme"><span class="header-section-number">1.2.1</span> Programme</a></li>
  <li><a href="#boilerplate-code" id="toc-boilerplate-code" class="nav-link" data-scroll-target="#boilerplate-code"><span class="header-section-number">1.2.2</span> Boilerplate Code</a></li>
  <li><a href="#bibliotheken" id="toc-bibliotheken" class="nav-link" data-scroll-target="#bibliotheken"><span class="header-section-number">1.2.3</span> Bibliotheken</a></li>
  <li><a href="#klassen-und-objekte" id="toc-klassen-und-objekte" class="nav-link" data-scroll-target="#klassen-und-objekte"><span class="header-section-number">1.2.4</span> Klassen und Objekte</a></li>
  <li><a href="#schlüsselwörter" id="toc-schlüsselwörter" class="nav-link" data-scroll-target="#schlüsselwörter"><span class="header-section-number">1.2.5</span> Schlüsselwörter</a></li>
  <li><a href="#objekte-erzeugen" id="toc-objekte-erzeugen" class="nav-link" data-scroll-target="#objekte-erzeugen"><span class="header-section-number">1.2.6</span> Objekte erzeugen</a></li>
  <li><a href="#methoden" id="toc-methoden" class="nav-link" data-scroll-target="#methoden"><span class="header-section-number">1.2.7</span> Methoden</a></li>
  <li><a href="#ein-objekt-für-die-led" id="toc-ein-objekt-für-die-led" class="nav-link" data-scroll-target="#ein-objekt-für-die-led"><span class="header-section-number">1.2.8</span> Ein Objekt für die LED</a></li>
  <li><a href="#zusammenfassung-unseres-ersten-programms" id="toc-zusammenfassung-unseres-ersten-programms" class="nav-link" data-scroll-target="#zusammenfassung-unseres-ersten-programms"><span class="header-section-number">1.2.9</span> Zusammenfassung unseres ersten Programms</a></li>
  <li><a href="#und-jetzt" id="toc-und-jetzt" class="nav-link" data-scroll-target="#und-jetzt"><span class="header-section-number">1.2.10</span> Und jetzt?</a></li>
  </ul></li>
  <li><a href="#farben-und-licht" id="toc-farben-und-licht" class="nav-link" data-scroll-target="#farben-und-licht"><span class="header-section-number">1.3</span> Farben und Licht</a></li>
  <li><a href="#farben-im-computer" id="toc-farben-im-computer" class="nav-link" data-scroll-target="#farben-im-computer"><span class="header-section-number">1.4</span> Farben im Computer</a></li>
  <li><a href="#farben-mischen" id="toc-farben-mischen" class="nav-link" data-scroll-target="#farben-mischen"><span class="header-section-number">1.5</span> Farben mischen</a>
  <ul class="collapse">
  <li><a href="#additive-farbmischung" id="toc-additive-farbmischung" class="nav-link" data-scroll-target="#additive-farbmischung"><span class="header-section-number">1.5.1</span> Additive Farbmischung</a></li>
  <li><a href="#subtraktive-farbmischung" id="toc-subtraktive-farbmischung" class="nav-link" data-scroll-target="#subtraktive-farbmischung"><span class="header-section-number">1.5.2</span> Subtraktive Farbmischung</a></li>
  </ul></li>
  <li><a href="#schleifen" id="toc-schleifen" class="nav-link" data-scroll-target="#schleifen"><span class="header-section-number">1.6</span> Schleifen</a>
  <ul class="collapse">
  <li><a href="#abzählbare-wiederholungen" id="toc-abzählbare-wiederholungen" class="nav-link" data-scroll-target="#abzählbare-wiederholungen"><span class="header-section-number">1.6.1</span> Abzählbare Wiederholungen</a></li>
  <li><a href="#bedingte-wiederholungen" id="toc-bedingte-wiederholungen" class="nav-link" data-scroll-target="#bedingte-wiederholungen"><span class="header-section-number">1.6.2</span> Bedingte Wiederholungen</a></li>
  </ul></li>
  <li><a href="#farbkreise" id="toc-farbkreise" class="nav-link" data-scroll-target="#farbkreise"><span class="header-section-number">1.7</span> Farbkreise</a>
  <ul class="collapse">
  <li><a href="#farbkreis-als-programm" id="toc-farbkreis-als-programm" class="nav-link" data-scroll-target="#farbkreis-als-programm"><span class="header-section-number">1.7.1</span> Farbkreis als Programm</a></li>
  <li><a href="#der-zyklus-wiederholt-sich" id="toc-der-zyklus-wiederholt-sich" class="nav-link" data-scroll-target="#der-zyklus-wiederholt-sich"><span class="header-section-number">1.7.2</span> Der Zyklus wiederholt sich</a></li>
  <li><a href="#zeitsteuerung" id="toc-zeitsteuerung" class="nav-link" data-scroll-target="#zeitsteuerung"><span class="header-section-number">1.7.3</span> Zeitsteuerung</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-colors" class="quarto-section-identifier"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Farben 🌈</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title"></div>
    <p>Das erste Kapitel hat es gleich in sich: Wir lernen etwas über Farben und wie sie im Computer funktionieren. Gleichzeitig steigen wir in die Programmierung ein und schreiben unser erstes Programm. Dabei nutzen wir eine LED und erzeugen einen Regenbogenfarbverlauf.</p>
  </div>
</div>


</header>


<section id="lernziele" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="lernziele">Lernziele</h2>
<p>Unsere wichtigsten Lernziele in diesem Kapitel sind:</p>
<ol type="1">
<li>Wir verstehen, wie Farben im Computer funktionieren.</li>
<li>Wir schreiben unser erstes Programm am Beispiel einer LED-Steuerung.</li>
<li>Wir lernen Schleifen in der Programmierung kennen.</li>
</ol>
</section>
<section id="experimentaufbau" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="experimentaufbau">Experimentaufbau</h2>
<p>Bereit für euer erstes Hardware-Experiment? Perfekt! Ihr braucht dafür eine LED (<a href="https://www.tinkerforge.com/en/doc/Hardware/Bricklets/RGB_LED_V2.html">RGB LED Bricklet 2.0</a>) und einen Mikrocontroller (<a href="https://www.tinkerforge.com/de/shop/master-brick.html">Master Brick 3.2</a>). Befestigt beide Bauteile mit Abstandshaltern auf einer Montageplatte, wie in <a href="#fig-setup-rgb-led" class="quarto-xref">Abbildung&nbsp;<span>1.1</span></a> gezeigt. Zwei Schrauben pro Gerät reichen völlig. Denkt an die kleinen, weißen Unterlegscheiben aus Kunststoff. Sie schützen eure Platinen vor Druckstellen.</p>
<p>Neben der Hardware benötigt ihr auch die passende Software. Diese solltet ihr bereits installiert haben. Falls nicht, schaut im <a href="./prerequisites.html">Abschnitt zu den Voraussetzungen</a> vorbei. Dort ist alles genau beschrieben. Im Folgenden gehe ich davon aus, dass ihr alles am Laufen habt.</p>
<div id="fig-setup-rgb-led" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-setup-rgb-led-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-setup-rgb-led" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-setup-rgb-led-a" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-group="setup-rgb-led">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-setup-rgb-led-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/master_brick_with_led_01.jpg" class="lightbox" data-gallery="setup-rgb-led" title="Abbildung&nbsp;1.1&nbsp;(a): Seitenansicht."><img src="images/master_brick_with_led_01.jpg" class="img-fluid figure-img" data-ref-parent="fig-setup-rgb-led"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-setup-rgb-led-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Seitenansicht.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-setup-rgb-led" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-setup-rgb-led-b" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-group="setup-rgb-led">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-setup-rgb-led-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/master_brick_with_led_02.jpg" class="lightbox" data-gallery="setup-rgb-led" title="Abbildung&nbsp;1.1&nbsp;(b): Nahaufnahme der LED."><img src="images/master_brick_with_led_02.jpg" class="img-fluid figure-img" data-ref-parent="fig-setup-rgb-led"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-setup-rgb-led-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Nahaufnahme der LED.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-setup-rgb-led" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-setup-rgb-led-c" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-group="setup-rgb-led">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-setup-rgb-led-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/master_brick_with_led_03.jpg" class="lightbox" data-gallery="setup-rgb-led" title="Abbildung&nbsp;1.1&nbsp;(c): Montageplatte mit allen Komponenten."><img src="images/master_brick_with_led_03.jpg" class="img-fluid figure-img" data-ref-parent="fig-setup-rgb-led"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-setup-rgb-led-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Montageplatte mit allen Komponenten.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-setup-rgb-led" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-setup-rgb-led-d" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-group="setup-rgb-led">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-setup-rgb-led-d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/master_brick_with_led_04.jpg" class="lightbox" data-gallery="setup-rgb-led" title="Abbildung&nbsp;1.1&nbsp;(d): Untenansicht."><img src="images/master_brick_with_led_04.jpg" class="img-fluid figure-img" data-ref-parent="fig-setup-rgb-led"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-setup-rgb-led-d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Untenansicht.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-setup-rgb-led" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-setup-rgb-led-e" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-group="setup-rgb-led">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-setup-rgb-led-e-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/master_brick_with_led_06.jpg" class="lightbox" data-gallery="setup-rgb-led" title="Abbildung&nbsp;1.1&nbsp;(e): Ansicht der vier Steckplätze."><img src="images/master_brick_with_led_06.jpg" class="img-fluid figure-img" data-ref-parent="fig-setup-rgb-led"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-setup-rgb-led-e-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e) Ansicht der vier Steckplätze.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-setup-rgb-led-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1.1: Einfaches Setup mit einem Mikrocontroller und einer LED.
</figcaption>
</figure>
</div>
</section>
<section id="erste-schritte-mit-der-led" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="erste-schritte-mit-der-led"><span class="header-section-number">1.1</span> Erste Schritte mit der LED</h2>
<p>Im ersten Schritt wollen wir die LED und ihre Funktionen testen! Das geht ganz leicht mit dem Brick Viewer. Schließt zuerst den Master Brick über das USB-Kabel an euren Computer an und öffnet den Brick Viewer. Klickt dann auf den Connect-Button.</p>
<div id="fig-brick-viewer-connect" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-group="brick-viewer">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brick-viewer-connect-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/brick_viewer_connect.png" class="lightbox" data-gallery="brick-viewer" title="Abbildung&nbsp;1.2: Über den Connect-Button verbindet ihr den Brick Viewer mit dem angeschlossenen Master Brick."><img src="images/brick_viewer_connect.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brick-viewer-connect-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1.2: Über den Connect-Button verbindet ihr den Brick Viewer mit dem angeschlossenen Master Brick.
</figcaption>
</figure>
</div>
<p>Wenn alles geklappt hat, zeigt euch der Brick Viewer alle angeschlossenen Geräte in Tabs an. Schaut euch <a href="#fig-brick-viewer-after-connect" class="quarto-xref">Abbildung&nbsp;<span>1.3</span></a> an – so etwa sollte es aussehen.</p>
<div id="fig-brick-viewer-after-connect" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-group="brick-viewer">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brick-viewer-after-connect-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/brick_viewer_after_connect.png" class="lightbox" data-gallery="brick-viewer" title="Abbildung&nbsp;1.3: Der Brick Viewer nachdem ihr mit dem Master Brick verbunden seid."><img src="images/brick_viewer_after_connect.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brick-viewer-after-connect-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1.3: Der Brick Viewer nachdem ihr mit dem Master Brick verbunden seid.
</figcaption>
</figure>
</div>
<p>Wechselt nun zum Tab der RGB LED. Hier könnt ihr über unterschiedliche Wege die Farbe der LED einstellen. Mehr kann eine LED nicht!</p>
<p>Mit den drei Schiebereglern steuert ihr die einzelnen Farbkanäle – Rot, Grün, Blau. Der Wertebereich: 0 bis 255. Warum gerade diese die Farben und Zahlen? Gute Frage. Die Antwort kommt weiter unten.</p>
<div id="fig-brick-viewer-rgb-led" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-group="brick-viewer">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brick-viewer-rgb-led-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/brick_viewer_rgb_led_button.png" class="lightbox" data-gallery="brick-viewer" title="Abbildung&nbsp;1.4: Die Ansicht für die RGB LED im Brick Viewer, in der ihr alle Funktionen per Klick im Zugriff habt."><img src="images/brick_viewer_rgb_led_button.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brick-viewer-rgb-led-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1.4: Die Ansicht für die RGB LED im Brick Viewer, in der ihr alle Funktionen per Klick im Zugriff habt.
</figcaption>
</figure>
</div>
<p>Fazit: Der Brick Viewer ist top zum Rumprobieren. Aber wenn ihr echte Projekte umsetzen wollt, müsst ihr programmieren lernen. Also los!</p>
</section>
<section id="unser-erstes-programm" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="unser-erstes-programm"><span class="header-section-number">1.2</span> Unser erstes Programm</h2>
<p>Wie verbinden wir uns über Programm mit der LED und setzen ihre Farbe? Die Antwort darauf findet ihr im folgenden kurzen Codebeispiel.</p>
<div id="4176b17d" class="cell" data-execution_count="1">
<div id="lst-boilerplate-code" class="python cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-boilerplate-code-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Listing&nbsp;1.1: Der Boilerplate-Code für die Verbindung mit den Geräten am Beispiel der RGB LED.
</figcaption>
<div aria-describedby="lst-boilerplate-code-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="sourceCode cell-code" id="annotated-cell-1"><pre class="sourceCode numberSource python code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode python"><button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="1">1</button><span id="annotated-cell-1-1" class="code-annotation-target"><a href="#annotated-cell-1-1"></a><span class="im">from</span> tinkerforge.ip_connection <span class="im">import</span> IPConnection</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="2">2</button><span id="annotated-cell-1-2" class="code-annotation-target"><a href="#annotated-cell-1-2"></a><span class="im">from</span> tinkerforge.bricklet_rgb_led_v2 <span class="im">import</span> BrickletRGBLEDV2</span>
<span id="annotated-cell-1-3"><a href="#annotated-cell-1-3"></a></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="3">3</button><span id="annotated-cell-1-4" class="code-annotation-target"><a href="#annotated-cell-1-4"></a>ipcon <span class="op">=</span> IPConnection()</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="4">4</button><span id="annotated-cell-1-5" class="code-annotation-target"><a href="#annotated-cell-1-5"></a>ipcon.<span class="ex">connect</span>(<span class="st">"localhost"</span>, <span class="dv">4223</span>)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="5">5</button><span id="annotated-cell-1-6" class="code-annotation-target"><a href="#annotated-cell-1-6"></a>led <span class="op">=</span> BrickletRGBLEDV2(<span class="st">"ZEP"</span>, ipcon)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</figure>
</div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-1" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="1" data-code-annotation="1">Hier importieren wir ein Objekt aus einer Bibliothek zum Herstellen einer Verbindung mit dem Master Brick.</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="2" data-code-annotation="2">Hier importieren wir ein weiteres Objekt, das wir zur Darstellung der LED als Python-Objekt benötigen.</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="4" data-code-annotation="3">Die Verbindung erfolgt über eine sogenannte IP-Verbindung, die wir hier als Objekt erstellen.</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="5" data-code-annotation="4">Mit <code>connect</code> stellen wir eine Verbindung zum angeschlossenen Master Brick her.</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="6" data-code-annotation="5">Schließlich holen wir uns eine virtuelle Instanz des RGB LED Bricklets, indem wir die UID nennen und sagen, welche Verbindung (<code>ipcon</code>) genutzt werden soll.</span>
</dd>
</dl>
</div>
</div>
<section id="programme" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="programme"><span class="header-section-number">1.2.1</span> Programme</h3>
<p>Zunächst klären wir den Begriff <em>Programm</em>. Ein Programm ist eine Abfolge von Anweisungen, die ein Computer ausführt, um eine bestimmte Aufgabe zu erledigen. In unserem Fall ist das Programm später dafür zuständig, mit der LED zu interagieren und sie in verschiedenen Farben leuchten zu lassen. Programme werden in Programmiersprachen geschrieben, die es uns ermöglichen, dem Computer präzise Anweisungen zu geben. Wir verwenden in diesem Buch die Programmiersprache Python, die sich besonders gut für Einsteiger eignet und gleichzeitig mächtig genug ist, um komplexe Aufgaben zu lösen.</p>
<p>Wenn wir ein Programm ausführen, arbeitet der Computer die Anweisungen Schritt für Schritt von oben nach unten ab. Die Nummerierung der Zeilen verdeutlicht das sehr schön. Der Computer beginnt bei Zeile 1 und arbeitet die Befehle Zeile für Zeile bis nach unten ab.</p>
<p>Es gibt Befehle, die den Computer von dieser linearen Abfolge abweichen lassen, etwa Schleifen oder Verzweigungen. Diese lernen wir später kennen.</p>
</section>
<section id="boilerplate-code" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="boilerplate-code"><span class="header-section-number">1.2.2</span> Boilerplate Code</h3>
<p>Der Codeausschnitt in <a href="#lst-boilerplate-code" class="quarto-xref">Listing&nbsp;<span>1.1</span></a> wird uns im Verlauf dieses Buches immer wieder begegnen. Wir benötigen ihn, um uns am Anfang des Programms mit den Geräten zu verbinden, die wir für unsere Anwendung benötigen. In der Informatik nennen wir solchen Code, den wir häufig in der gleichen Form benötigen und fast eins zu eins kopieren können, auch <em>Boilerplate-Code</em>. Wundert euch also nicht, wenn ich diesen Begriff ab und an mal verwende. Jetzt wisst ihr, was gemeint ist.</p>
</section>
<section id="bibliotheken" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="bibliotheken"><span class="header-section-number">1.2.3</span> Bibliotheken</h3>
<p>Beginnen wir in den ersten beiden Zeilen. Hier seht ihr zwei sehr ähnliche Befehle, die mit dem Schlüsselwort <code>from</code> beginnen. Nach dem Schlüsselwort <code>from</code> folgt der Name einer Bibliothek, aus der wir ein für unser Programm benötigtes Objekte importieren. Die Kombination der Schlüsselwörter <code>from ...import</code> lässt sich also wörtlich übersetzen: “Aus der Bibliothek X importiere das Objekt Y”.</p>
<p>Eine <em>Bibliothek</em> in einer Programmiersprache ist die Bündelung und Bereitstellung von Funktionen, Klassen oder Konstanten. Eine Bibliothek könnt ihr euch vorstellen wie einen Werkzeugkasten: Sie enthält fertige Werkzeuge (Funktionen und Klassen), damit ihr nicht alles von Grund auf selbst programmieren müsst. Tinkerforge stellt uns genau solche Werkzeuge bereit, damit wir schnell und unkompliziert mit den Geräten loslegen können. Für jedes Gerät gibt es in der Tinkerforge-Bibliothek eine eigene Klasse, über die wir auf die Funktionen jedes Geräts zugreifen können.</p>
</section>
<section id="klassen-und-objekte" class="level3" data-number="1.2.4">
<h3 data-number="1.2.4" class="anchored" data-anchor-id="klassen-und-objekte"><span class="header-section-number">1.2.4</span> Klassen und Objekte</h3>
<p>Mit <code>from ... import</code> importieren wir also etwas aus einer Bibliothek. Soweit so gut. Aber was bedeutet das genau? Mit <em>importieren</em> ist konkret gemeint, dass wir dem Programm mitteilen, dass wir vorhaben, die genannten Dinge in unserem Programm zu verwenden, und dass sie deshalb am besten schon einmal geladen werden sollten. Ob wir diese Dinge später wirklich nutzen steht auf einem anderen Blatt.</p>
<p>In dem Fall der ersten beiden Zeilen unseres Programms von oben sind es zwei <em>Klassen</em>, deren Verwendung wir ankündigen. Die erste Klasse heisst <code>IPConnection</code> und die zweite <code>BrickletRGBLEDV2</code>. Der Begriff <em>Klasse</em> ist hier analog zum Begriff <em>Kategorie</em> zu verstehen. Wir können zu einer Klasse gehörige <em>Objekte</em> erzeugen, und alle Objekte der selben Klasse verhalten sich gleich und haben die gleichen Funktionen. Das verstehen wir am besten an einem einfachen Beispiel.</p>
<p>Stellt euch vor, ihr habt eine Klasse namens <code>Auto</code>. Diese Klasse beschreibt alle Eigenschaften und Funktionen, die ein Auto haben kann, wie etwa <code>fahren()</code>, <code>bremsen()</code> oder <code>tanken()</code>. Diese Dinge sollen für jedes Auto gleich ablaufen. Jedes konkrete Auto in der Welt ist ein Objekt dieser Klasse. Wir können also sagen: “Mein Auto ist ein Objekt der Klasse <code>Auto</code>.” Jedes <code>Auto</code> hat neben den Funktionen die gleichen Eigenschaften wie Farbe, Marke und Modell. Aber jedes Auto kann andere Werte für diese Eigenschaften haben.</p>
<p>Genauso verhält es sich mit den Klassen, die Tinkerforge für uns bereitgestellt hat. Die Klasse <code>IPConnection</code> beschreibt, wie wir eine Verbindung zu einem Mikrocontroller herstellen können, und die Klasse <code>BrickletRGBLEDV2</code> beschreibt, wie wir mit der LED interagieren können. Wenn wir ein Objekt dieser Klasse erstellen, können wir alle Funktionen nutzen, die in der Klasse definiert sind. Eine LED muss nicht fahren oder bremsen wie ein Auto. Dafür hat sie andere Funktionen, wie etwa <code>set_rgb_value()</code>, die uns erlaubt, die Farbe der LED zu ändern. Eine Eigenschaft jeder LED ist ihre UID, die eindeutig ist und uns hilft, sie im System zu identifizieren.</p>
</section>
<section id="schlüsselwörter" class="level3" data-number="1.2.5">
<h3 data-number="1.2.5" class="anchored" data-anchor-id="schlüsselwörter"><span class="header-section-number">1.2.5</span> Schlüsselwörter</h3>
<p>Soeben haben wir mit <code>from</code> und <code>import</code> unsere ersten beiden Schlüsselwörter in Python kennengelernt! Aber was bedeutet das genau? Ein Schlüsselwort, das wir im Englischen auch <em>keyword</em> oder <em>reserved keyword</em> nennen, ist ein Begriff, der in der jeweiligen Programmiersprache eine feste Bedeutung hat und deshalb nicht anderweitig verwendet werden darf. Wir werden gleich noch sehen, dass wir bei der Programmierung auch häufig Namen vergeben müssen, etwa für Variablen oder Funktionen. Diese Namen dürfen nicht wie ein Schlüsselwort lauten, ansonsten funktioniert unser Programm nicht wie gewünscht. Welche Schlüsselwörter es in Python gibt, könnt ihr <a href="https://docs.python.org/3/reference/lexical_analysis.html#keywords" title="Reservierte Schlüsselwörter in Python">hier</a> nachschauen.</p>
<p>Im Codeausschnitt oben laden wir zuerst das Objekt für die Verbindung zum angeschlossenen Mikrocontroller, die über eine IP-Verbindung hergestellt wird. Was das genau ist? Später mehr dazu. Zusätzlich zur <code>IPConnection</code> laden wir anschließend noch die benötigen Klassen für die Geräte, die wir in unserem aktuellen Setup verwenden wollen. In diesem Kapitel ist das nur die LED, in späteren Experimenten werden es auch mal mehrere Geräte sein.</p>
</section>
<section id="objekte-erzeugen" class="level3" data-number="1.2.6">
<h3 data-number="1.2.6" class="anchored" data-anchor-id="objekte-erzeugen"><span class="header-section-number">1.2.6</span> Objekte erzeugen</h3>
<p>In <a href="#lst-boilerplate-code" class="quarto-xref">Listing&nbsp;<span>1.1</span></a> in Zeile 4 erzeugen wir ein Objekt der Klasse <code>IPConnection</code>. Die fertige Instanz - so nennen wir ein Objekt, das aus einer Klasse erzeugt wurde - speichern wir auf einer <em>Variable</em> mit dem Namen <code>ipcon</code>. Diesen Namen haben wir uns selbst ausgedacht, damit wir später darauf zugreifen können. Wir hätten auch einen anderen Namen wählen können.Eine Variable ist also ein Platzhalter für einen Wert, den wir später im Programm verwenden wollen. In diesem Fall ist <code>ipcon</code> der Platzhalter für die Verbindung zu unserem Mikrocontroller. Was eine Variable technisch ist, lernen wir später noch genauer kennen.</p>
</section>
<section id="methoden" class="level3" data-number="1.2.7">
<h3 data-number="1.2.7" class="anchored" data-anchor-id="methoden"><span class="header-section-number">1.2.7</span> Methoden</h3>
<p>Über das Objekt <code>ipcon</code> können wir nun eine Verbindung zu unserem Mikrocontroller herstellen. Das geschieht in Zeile 5 mit der Methode <code>connect()</code>. Eine <em>Methode</em> ist eine Funktion, die zu einem Objekt gehört. Wie etwa <code>fahren()</code> oder <code>bremsen()</code> in unserem Auto-Beispiel.</p>
<p>Wir können Methoden aufrufen, um eine bestimmte Aktion auszuführen. In diesem Fall stellen wir eine Verbindung zum Mikrocontroller her, indem wir die Adresse und den Port angeben, über den die Verbindung hergestellt werden soll. In unserem Fall ist das “localhost”, was für die lokale Maschine steht, und Port 4223, der durch den Brick Daemon standardmäßig so konfiguriert ist. Der Aufruf einer Methode erfolgt immer mit dem Punkt <code>.</code> nach dem Objekt, gefolgt vom Namen der Methode und den Klammern <code>()</code>, in denen wir eventuell benötigte Parameter angeben.</p>
<p>Eine Methode ist letztlich eine Funktion, die zu einem Objekt gehört. Zu einem späteren Zeitpunkt schreiben wir unsere eigenen Funktionen und lernen dann noch viel mehr darüber.</p>
</section>
<section id="ein-objekt-für-die-led" class="level3" data-number="1.2.8">
<h3 data-number="1.2.8" class="anchored" data-anchor-id="ein-objekt-für-die-led"><span class="header-section-number">1.2.8</span> Ein Objekt für die LED</h3>
<p>In Zeile 6 erzeugen wir schließlich ein Objekt der Klasse <code>BrickletRGBLEDV2</code>. Dieses Objekt repräsentiert unsere LED und ermöglicht es uns, mit ihr zu interagieren. Wir nennen das Objekt <code>led</code>, was kurz und klar ist. Auch hier haben wir uns den Namen selbst ausgedacht, um später darauf zugreifen zu können. Auch wenn wir grundsätzlich Variablennamen frei wählen können, sollten sie immer so gewählt werden, dass sie den Inhalt der Variable beschreiben. Das macht es später einfacher, den Code zu verstehen. Gleichzeitig gibt es in Python einige Regeln, die wir bei der Benennung von Variablen beachten müssen. Dazu gehören etwa, dass Variablennamen nicht mit einer Zahl beginnen dürfen und keine Leerzeichen enthalten dürfen. Eine ausführliche Liste der Regeln findet ihr <a href="https://docs.python.org/3/reference/lexical_analysis.html#identifiers" title="Regeln für Variablennamen in Python">hier</a>.</p>
</section>
<section id="zusammenfassung-unseres-ersten-programms" class="level3" data-number="1.2.9">
<h3 data-number="1.2.9" class="anchored" data-anchor-id="zusammenfassung-unseres-ersten-programms"><span class="header-section-number">1.2.9</span> Zusammenfassung unseres ersten Programms</h3>
<p>Damit haben wir unser erstes Programm von oben nach unten erläutert und dabei schon viele wichtige Konzepte der Programmierung kennengelernt:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 69%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Programme</strong></td>
<td>Abfolge von Anweisungen, die nacheinander ausgeführt werden.</td>
</tr>
<tr class="even">
<td><strong>Boilerplate Code</strong></td>
<td>Standard-Code, den man immer wieder braucht.</td>
</tr>
<tr class="odd">
<td><strong>Importieren von Bibliotheken</strong></td>
<td>Sammlung von fertigen Code-Elementen.</td>
</tr>
<tr class="even">
<td><strong>Schlüsselwörter</strong></td>
<td>Reservierte Begriffe der Programmiersprache.</td>
</tr>
<tr class="odd">
<td><strong>Klassen und Objekte</strong></td>
<td>Kategorien und deren konkrete Instanzen.</td>
</tr>
<tr class="even">
<td><strong>Methoden und Funktionen</strong></td>
<td>Funktionen, die zu einem Objekt gehören.</td>
</tr>
<tr class="odd">
<td><strong>Variablen</strong></td>
<td>Platzhalter für Werte.</td>
</tr>
</tbody>
</table>
</section>
<section id="und-jetzt" class="level3" data-number="1.2.10">
<h3 data-number="1.2.10" class="anchored" data-anchor-id="und-jetzt"><span class="header-section-number">1.2.10</span> Und jetzt?</h3>
<p>Wir haben nun eine digitale Repräsentation unserer LED in Python. Wir können die LED jetzt zum Leuchten bringen, indem wir eine Methode der Klasse <code>BrickletRGBLEDV2</code>, die <code>set_rgb_value()</code> heißt, verwenden. Diese Methode erwartet drei Parameter: Rot, Grün und Blau. Mit diesen Parametern können wir die Farbe der LED einstellen.</p>
<div id="2f989d8b" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="annotated-cell-2"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><button class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="1">1</button><span id="annotated-cell-2-1" class="code-annotation-target"><a href="#annotated-cell-2-1" aria-hidden="true" tabindex="-1"></a>led.set_rgb_value(<span class="dv">0</span>, <span class="dv">255</span>, <span class="dv">0</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-2" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="1" data-code-annotation="1">Setzt die LED auf grün. R = 0, G = 255, B = 0. Logisch, oder?</span>
</dd>
</dl>
</div>
</div>
<p>Moment mal … Wo steht hier eigentlich <em>grün</em>? Steht da gar nicht. Stattdessen drei Zahlen. Willkommen bei der <em>RGB-Farbkodierung</em>. Jede Farbe besteht aus drei Werten zwischen 0 und 255: Rot, Grün, Blau. Null ist nix. 255 ist volle Power. Alles 0? Schwarz. Alles 255? Weiß. Nur Grün auf 255? Na klar: grün.</p>
<p>Aber warum machen wir das mit Zahlen? Weil Computer nun mal mit Zahlen arbeiten. Das ist einer der zentralen Gedanken dieses Buches: Wie übersetzen wir die Welt in etwas, das ein Computer versteht?</p>
<p>Warum aber ist das so? Warum kodieren wir in der Informatik jede Farbe mit <em>drei</em> Zahlen? Warum überhaupt mit Zahlen? Hier kommen wir zu einer zentralen Frage dieses Buches: Wie bilden Computer Informationen ab?</p>
<p>Vorher müssen wir aber kurz zurück in die Schule.</p>
</section>
</section>
<section id="farben-und-licht" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="farben-und-licht"><span class="header-section-number">1.3</span> Farben und Licht</h2>
<p>Physik ist vielleicht schon eine Weile her. Erinnern wir uns dennoch kurz, was Licht ist und wie Farben damit zusammenhängen. Licht ist <em>elektromagnetische Strahlung</em>. Das bedeutet, es handelt sich um gekoppelte Schwingungen elektrischer und magnetischer Felder, die sich mit Lichtgeschwindigkeit ausbreiten. Vereinfacht können wir uns Licht als Wellen vorstellen, die sich durch den Raum bewegen. Diese Wellen haben unterschiedliche Frequenzen und Wellenlängen. Das sichtbare Licht ist nur ein kleiner Teil des gesamten elektromagnetischen Spektrums, das von Radiowellen über Infrarotstrahlung bis hin zu Röntgenstrahlen und Gammastrahlen reicht.</p>
<p>Bei Wellen unterscheiden wir zwischen der Frequenz (wie oft die Welle pro Sekunde schwingt) und der Wellenlänge (der Abstand zwischen zwei aufeinanderfolgenden Wellenbergen). Die Frequenz und die Wellenlänge sind umgekehrt proportional: Je höher die Frequenz, desto kürzer die Wellenlänge und umgekehrt.</p>
<p>Frequenzen messen wir in Hertz (Hz), wobei 1 Hz einer Schwingung pro Sekunde entspricht. Das sichtbare Licht hat Frequenzen im Bereich von etwa 430 THz (Terahertz) bis 750 THz. Die Wellenlängen des sichtbaren Lichts liegen zwischen etwa 400 nm (Nanometer) für violettes Licht und etwa 700 nm für rotes Licht. Um sich das vorzustellen: Ein Nanometer ist ein Milliardstel Meter. Zum Vergleich: Ein menschliches Haar hat einen Durchmesser von etwa 80.000 bis 100.000 Nanometern. Die Abstände zwischen den Wellenlängen des sichtbaren Lichts sind also extrem klein.</p>
<p>Was bedeutet das nun für eine LED? Eine LED (Light Emitting Diode) ist ein Halbleiterbauelement, das Licht erzeugt, wenn elektrischer Strom hindurchfließt. Die Farbe des Lichts hängt von Eigenschaften des Halbleitermaterials ab, aus dem die LED besteht. Verschiedene Materialien emittieren Licht bei unterschiedlichen Wellenlängen, was zu verschiedenen Farben führt. Zum Beispiel emittiert eine rote LED Licht mit einer Wellenlänge von etwa 620-750 nm, während eine grüne LED Licht mit einer Wellenlänge von etwa 495-570 nm emittiert.</p>
<div id="fig-em-spectrum" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-em-spectrum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/em_spectrum.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-em-spectrum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1.5: Das elektromagnetische Spektrum, wovon das sichtbare Licht ein kleiner Teil ist. (Quelle: <a href="https://en.wikipedia.org/wiki/File:EM_Spectrum_Properties_edit.svg">Wikipedia</a>)
</figcaption>
</figure>
</div>
<p>Die RGB LED besteht in Wirklichkeit aus drei einzelnen LEDs: einer roten, einer grünen und einer blauen. Jede dieser LEDs kann unabhängig voneinander angesteuert werden, um verschiedene Farben zu erzeugen. Mehr Stromstärke bedeutet mehr Intensität der jeweiligen Farbe. Durch die Kombination der drei Grundfarben Rot, Grün und Blau in unterschiedlichen Intensitäten können wir eine Vielzahl von Farben mischen. Das ist das Prinzip der additiven Farbmischung: Wenn wir alle drei Farben mit voller Intensität leuchten lassen, erhalten wir Weiß. Wenn wir keine Farbe leuchten lassen, erhalten wir Schwarz. Klar, die LED sind dann alle aus.</p>
</section>
<section id="farben-im-computer" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="farben-im-computer"><span class="header-section-number">1.4</span> Farben im Computer</h2>
<p>Nun wissen wir, warum die Methode <code>set_rgb_value()</code> drei Parameter erwartet: Rot, Grün und Blau. Diese Parameter sind die Intensitäten der jeweiligen Farbe, die wir in unserem Programm angeben. Mit den Werten 0 bis 255 können wir jede Farbe im sichtbaren Spektrum erzeugen.</p>
<p>Wie kommt es aber zu der merkwürdigen Zahl 255? Warum nicht einfach 0 bis 100? Das liegt daran, wie ein Computer grundsätzlich Werte speichert und wie dieser Speicher organisiert ist. Kurz gesagt: Der Wertebereich 0 bis 255 passt genau in ein sogenanntes <em>Byte</em>. Ein Byte ist eine Speichereinheit, die aus 8 Bits besteht. Ein Bit kann entweder 0 oder 1 sein. Mit 8 Bits können wir also <span class="math inline">\(2^8 = 256\)</span> verschiedene Werte darstellen, von 0 bis 255. Das ist genau der Bereich, den wir für die RGB-Farbkodierung verwenden. Dazu lernen wir später noch mehr.</p>
<p>Wir halten also fest, dass sich ein Farbwert im Computer aus drei Zahlen zusammensetzt, die jeweils zwischen 0 und 255 liegen. Das gilt für unsere LED, aber auch für Pixel in TVs, Smartphones, digitalen Foto oder Monitoren. All diese Dinge beleuchten wir später noch genauer.</p>
</section>
<section id="farben-mischen" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="farben-mischen"><span class="header-section-number">1.5</span> Farben mischen</h2>
<p>Klingt alles theoretisch sehr gut. Aber wie sieht es mit der Praxis aus? Probieren wir es aus und mischen zwei Farben mit voller Intensität!</p>
<div id="6299a3bb" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>led.set_rgb_value(<span class="dv">255</span>, <span class="dv">255</span>, <span class="dv">0</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Was macht der Befehl? Welche Farbe kommt dabei heraus? Probiert es einfach mal aus!</p>
<section id="additive-farbmischung" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="additive-farbmischung"><span class="header-section-number">1.5.1</span> Additive Farbmischung</h3>
<p>Ihr solltet alle eure LEDs in Gelb aufleuchten sehen. In der <em>additiven Farbmischung</em> mischen wir Rot und Grün und erhalten dadurch Gelb. Gelb ist heller als die beiden Farben Rot und Grün, was kein Zufall ist. Das ist das Prinzip der additiven Farbmischung: Wenn wir zwei Farben mit voller Intensität leuchten lassen, erhalten wir eine neue Farbe, die stest heller ist als die Ursprungsfarben. Wir fügen mehr Licht hinzu. Wenn wir alle drei Farben mit voller Intensität mischen erhalten wir schließlich Weiß.</p>
<div id="da5873aa" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>led.set_rgb_value(<span class="dv">255</span>, <span class="dv">255</span>, <span class="dv">255</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Am anderen Ende des Spektrums erzeugen drei Nullen die Farbe Schwarz:</p>
<div id="988b62bd" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>led.set_rgb_value(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="subtraktive-farbmischung" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="subtraktive-farbmischung"><span class="header-section-number">1.5.2</span> Subtraktive Farbmischung</h3>
<p>Ihr könnt euch merken, dass wir im Kontext von Computern oft von <em>additiver Farbmischung</em> sprechen, weil Bildschirme Licht erzeugen. Durch das Mischen der drei Farbkanäle entstehen neue Farben gemäß der additiven Farbmischung, also stets heller als ihre Grundfarben. Daneben gibt es aber noch die subtraktive Farbmischung. Sie funktioniert anders, nämlich genau umgekehrt. Statt beim Mischen Licht hinzuzufügen, nehmen wir Licht weg.</p>
<p>Erinnert ihr euch an euren Farbkasten aus der Grundschule? Dort habt ihr auch Farben gemischt, um neue Farben zu erzeugen, die euer Farbkasten nicht direkt mitgeliefert hat. Was hat im Farbenkasten die Mischung aus Rot und Grün ergeben? Sicher nicht Gelb - eher Braun. Eine dunklere Farbe. Das liegt daran, dass wir es hier nicht mit additiver, sondern mit subtraktiver Farbmischung zu tun haben. Bei der subtraktiven Farbmischung mischen wir Pigmente, die Licht <em>absorbieren</em> und <em>reflektieren</em>. Das Mischen von Farben fungiert hier wie ein Filter: Bestimmte Teile des Lichtspektrums werden nicht mehr reflektiert, sondern absorbiert und sind damit nicht mehr sichtbar. Das Ergebnis einer Mischung zweier Farben ergibt in der subtraktiven Farbmischung also stets eine dunklere Farbe. Genau umgekehrt zur additiven Farbmischung.</p>
<p>Was passiert mit dem absorbierten Licht? Es wird in eine andere Form der Energie umgewandelt, nämlich Wärme. Deshalb wird eine schwarze Oberfläche auch besonders heiß, wenn die Sonne darauf knallt. Sie absorbiert das gesamte Lichtspektrum und wandelt es in Wärme um. Dagegen wirken weiße Oberflächen fast wie Klimaanlagen. Es ist kein Zufall, dass wir in sonnigen Erdteilen viele weiße Fassaden sehen.</p>
<p>Wenn wir alle Farben mischen ergibt die subtraktive Farbmischung Schwarz, weil kein Licht mehr reflektiert wird. Alles Licht wird aufgesogen und nichts kommt mehr zurück. Das ist ein anderes Prinzip als bei der additiven Farbmischung, bei der wir Lichtquellen <em>kombinieren</em>, um neue Farben zu erhalten.</p>
<div id="fig-color-mixing" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-color-mixing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-color-mixing" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-additive-color-mixing" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-additive-color-mixing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/additive_color_mixing.png" class="lightbox" data-gallery="fig-color-mixing" title="Abbildung&nbsp;1.6&nbsp;(a): Additive Farbmischung"><img src="images/additive_color_mixing.png" class="img-fluid figure-img" data-ref-parent="fig-color-mixing"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-additive-color-mixing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Additive Farbmischung
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-color-mixing" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-subtractive-color-mixing" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-subtractive-color-mixing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/subtractive_color_mixing.png" class="lightbox" data-gallery="fig-color-mixing" title="Abbildung&nbsp;1.6&nbsp;(b): Subtraktive Farbmischung"><img src="images/subtractive_color_mixing.png" class="img-fluid figure-img" data-ref-parent="fig-color-mixing"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-subtractive-color-mixing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Subtraktive Farbmischung
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-color-mixing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1.6: Additive und subtraktive Farbmischung.
</figcaption>
</figure>
</div>
<p>In <a href="#fig-color-mixing" class="quarto-xref">Abbildung&nbsp;<span>1.6</span></a> sehen wir die beiden Farbmischungsarten im Vergleich. In <a href="#fig-subtractive-color-mixing" class="quarto-xref">Abbildung&nbsp;<span>1.6 (b)</span></a> sehen wir die drei Grundfarben, die wir bei der subtraktiven Variante benötigen, um daraus alle weiteren Farben zu erhalten. Das sind Cyan, Magenta sowie Gelb. Im Englischen ist die Abkürzung CMY, wo das “Y” für <em>Yellow</em> steht. In der additiven Farbmischung sind es, wie oben schon gesehen, Rot, Grün und Blau. Wenn ihr <a href="#fig-additive-color-mixing" class="quarto-xref">Abbildung&nbsp;<span>1.6 (a)</span></a> betrachtet dann erkennt ihr, dass genau diese drei Farben durch das Mischen jeweils zweier Grundfarben in der additiven Farbmischung entstehen. Und umgekehrt gilt das gleiche Prinzip! Ob das Zufall ist?</p>
<p>In der additiven Farbmischung entsteht Gelb durch das Mischen von Rot und Grün, wobei Blau fehlt. Im Umkehrschluss bedeutet das: Gelbes Licht enthält keine blaue Komponente, es reflektiert also kein Blau. In der subtraktiven Farbmischung (wie beim Farbkasten) wird Gelb erzeugt, indem Blau aus weißem Licht herausgefiltert wird – Gelb reflektiert also kein Blau, sondern absorbiert es. Gelb kann also auch als Blaufilter gesehen werden. Das erklärt, warum ein gelber Gegenstand unter blauem Licht dunkel erscheint: Er kann das blaue Licht nicht reflektieren.</p>
<p>Jetzt können wir auch erklären, warum Farbdrucker vier unterschiedliche Kartuschen benötigen (<a href="#fig-toner-cmy" class="quarto-xref">Abbildung&nbsp;<span>1.7</span></a>). Mit den Grundfarben der subtraktiven Farbmischung Cyan, Magenta und Gelb können wir jede beliebige Farbe mischen. Zusätzlich haben Drucker eine Kartusche für Schwarz, um erstens ein sattes Schwarz drucken zu können und zweitens die Farbkartuschen zu schonen. Denn schließlich müssen alle drei Farben gemischt werden, um Schwarz zu erhalten. Und weil viele Drucksachen schwarz enthalten (oder sogar ausschließlich) ist eine schwarze Kartusche einfach effizienter. Die Farbe Schwarz wird bei Druckerkartuschen als Key bezeichnet und mit “K” abgekürzt. Wir sprechen daher auch von CMYK.</p>
<div id="fig-toner-cmy" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-toner-cmy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/toner-cmy.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Abbildung&nbsp;1.7: Ein typisches Set mit CMY-Druckerkartuschen inklusive Schwarz."><img src="images/toner-cmy.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-toner-cmy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1.7: Ein typisches Set mit CMY-Druckerkartuschen inklusive Schwarz.
</figcaption>
</figure>
</div>
<p>Farben spielen eine so wichtige Rolle bei der Arbeit mit Computern. Deshalb lohnt es sich, ein wenig über die Hintergründe von Farben und deren Mischung zu verstehen. Wir werden später noch lernen, wie Bildschirme Farben darstellen. Spätestens dann wird uns das Thema der Farbmischung wieder begegnen.</p>
<p>Ab jetzt wollen wir weiter mit unserer LED experimentieren und den RGB-Code, mit dem Computer Farben abbilden, praxisnah verstehen. Bisher haben wir gelernt, dass wir die Farbe der LED über die Methode <code>set_rgb_value()</code> verändern können, wenn wir wissen, welcher RGB-Code unsere gewünschte Farbe repräsentiert. Da wir jetzt mehr über die Farbmischung wissen, können wir die LED also ganz einfach in der Farbe Magenta leuchten lassen:</p>
<div id="d8d93428" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>led.set_rgb_value(<span class="dv">255</span>, <span class="dv">0</span>, <span class="dv">255</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Gemäß der Theorie der additiven Farbmischung (<a href="#fig-additive-color-mixing" class="quarto-xref">Abbildung&nbsp;<span>1.6 (a)</span></a>) müsste Rot und Blau Magenta ergeben. Probiert es aus!</p>
</section>
</section>
<section id="schleifen" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="schleifen"><span class="header-section-number">1.6</span> Schleifen</h2>
<p>Das deklarierte Ziel unseres ersten Experiments ist es, einen Regenbogenfarbverlauf zu erzeugen. Dazu müssen wir die Farbe der LED kontinuierlich ändern, sodass sie von Rot über Gelb, Grün, Cyan, Blau und Violett wieder zurück zu Rot wechselt. Das erreichen wir mit einer <em>Schleife</em>. Eine Schleife ist ein Konstrukt in der Programmierung, das es uns ermöglicht, einen bestimmten Codeabschnitt mehrfach auszuführen, ohne ihn jedes Mal neu schreiben zu müssen. Das spart Zeit und macht den Code übersichtlicher.</p>
<section id="abzählbare-wiederholungen" class="level3" data-number="1.6.1">
<h3 data-number="1.6.1" class="anchored" data-anchor-id="abzählbare-wiederholungen"><span class="header-section-number">1.6.1</span> Abzählbare Wiederholungen</h3>
<p>Wir beginnen wie immer einfach und nähern uns dem Regenbogen schrittweise an. Zunächst wäre es schön, wenn wir die LED einfach Rot pulsieren lassen könnten. Dazu müssen wir nämlich nur den Rot-Kanal und nicht alle drei Kanäle der LED ansteuern. Gleichzeitig lernen wir schon hier ein Problem kennen, das mit Schleifen gelöst werden kann.</p>
<p>Was bedeutet es, die LED pulsieren zu lassen? Und was müssen wir dafür tun? Pulsieren bedeutet, dass die LED langsam immer heller wird, kurz in der vollen Helligkeit verweilt, aber dann sofort wieder kontinuierlich dunkler wird. Sobald sie schwarz ist fängt der Zyklus von Vorne an.</p>
<p>Den Ausdruck <em>immer heller werden</em> können wir bezogen auf die LED so übersetzen, dass wir den Anteil des Rot-Kanals schrittweise erhöhen. Wenn die LED zu Beginn aus ist, also alle Kanäle auf 0 stehen, können wir den Rot-Kanal von 0 auf 255 erhöhen und so die LED immer heller in Rot aufleuchten lassen.</p>
<p>Wir beginnen also mit einer schwarzen LED:</p>
<div id="bbfc3081" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>led.set_rgb_value(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Anschließend setzen wir den Wert für Rot auf 1:</p>
<div id="b5035634" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>led.set_rgb_value(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Und erhöhen ihn schrittweise:</p>
<div id="b935db93" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>led.set_rgb_value(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>led.set_rgb_value(<span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>led.set_rgb_value(<span class="dv">4</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ...</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wenn wir nach diesem Muster fortfahren, hätten wir bis zum vollen Rot 255 Zeilen Code geschrieben, eine für Zeile jeden Erhöhungschritt. Und anschließend das gleiche nochmal rückwärts, damit wir wieder zu Schwarz kommen. Mit 510 Zeilen Code hätten wir dann eine Pulsierungszyklus durchlaufen. Wollen wir die LED öfters pulsieren lassen vervielfacht sich unser Code entsprechend. Das kann doch nicht die Lösung für ein so einfaches Problem sein.</p>
<p>Und tatsächlich gibt es in der Programmierung eine bessere Möglichkeit, um sich wiederholende Abläufe abzubilden: die Schleife. In einem Fall, bei dem wir genau wissen, wie oft wir etwas wiederholen wollen, bietet sich eine Zählerschleife an:</p>
<div id="0f983f68" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    led.set_rgb_value(r, <span class="dv">0</span>, <span class="dv">0</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Voilá! Unsere 510 Zeilen Code können wir mit einer Schleife auf zwei Zeilen reduzieren! Dazu müssen wir im Kopf der Schleife (<code>for ... in ...</code>) festlegen, wie oft der eingerückte Codeblock nach dem Doppelpunkt ausgeführt werden soll. In Python funktioniert das über die Angabe einer Menge, für die jedes Element einmal durchlaufen wird. Das aktuelle Element ist in der Schleife als <code>r</code> verfügbar. Und <code>r</code> nimmt nacheinander jeden Wert der Menge an, die nach dem Schlüsselwort <code>in</code> folgt. Diese Menge erzeugt hier die Funktion <code>range(256)</code>, die, wie der Name preisgibt, eine <em>Zahlensequenz</em> von 0 bis zum angegebenen Wert minus eins erzeugt. In unserem Fall also von 0 bis 255.</p>
<p>Um das besser nachvollziehen zu können, geben wir den Wert für <code>r</code> einfach mal aus:</p>
<div id="b92cfffe" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="annotated-cell-11"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-11-1"><a href="#annotated-cell-11-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="annotated-cell-11-2"><a href="#annotated-cell-11-2" aria-hidden="true" tabindex="-1"></a>    led.set_rgb_value(r, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="1">1</button><span id="annotated-cell-11-3" class="code-annotation-target"><a href="#annotated-cell-11-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(r)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-11" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="3" data-code-annotation="1">Mit <code>print()</code> geben wir einen Wert auf der Konsole aus.</span>
</dd>
</dl>
</div>
</div>
<p>Jetzt wird es deutlich: mit jedem Durchlauf der Schleife wird ein neuer Wert für <code>r</code> gesetzt und ausgegeben. Und zwar jeweils um eins erhöht. Die Funktion <code>range(256)</code> erzeugt genau gesagt eine sortierte Reihe mit den Zahlen von 0 bis 255. Das sieht in Python dann so aus:</p>
<div id="e767c8ee" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="annotated-cell-12"><pre class="sourceCode numberSource python code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-12-1"><a href="#annotated-cell-12-1"></a>list_of_numbers <span class="op">=</span> <span class="bu">range</span>(<span class="dv">256</span>)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="1">1</button><span id="annotated-cell-12-2" class="code-annotation-target"><a href="#annotated-cell-12-2"></a><span class="bu">print</span>(<span class="bu">list</span>(list_of_numbers))</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-12" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="2" data-code-annotation="1">Mit der <code>list()</code>-Funktion wandeln wir die von <code>range()</code> erzeugte Menge in eine Liste um, die wir dann ausgeben können.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255]</code></pre>
</div>
</div>
<p>Rückwärts erreichen wir das gleiche Ergebnis mit einer weiteren Schleife, deren Menge wir umkehren, so dass sie von 255 bis 0 geht:</p>
<div id="eca030aa" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1"></a><span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb10-2"><a href="#cb10-2"></a>    led.set_rgb_value(r, <span class="dv">0</span>, <span class="dv">0</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Warum hat <code>range()</code> auf einmal drei Argumente? Ganz einfach: Standardmäßig erstellt die Funktion eine Menge von 0 bis zur angegebenen Zahl minus eins. Wir können die Menge aber beeinflussen, indem wir einen Startwert und einen Schrittwert angeben. In unserem Fall oben beginnen wir bei 255 (erster Parameter) und gehen bis -1 (zweiter Parameter), wobei wir in jedem Schritt um -1 verringern (dritter Parameter). Warum zählen wir bis -1, wo wir doch eigentlich die 0 als kleinste Zahl benötigen? Das liegt daran, dass die Menge von <code>range()</code> immer bis zum zweiten Parameter minus eins geht. Wenn wir also 0 als kleinste Zahl benötigen, müssen wir bis -1 zählen.</p>
<p>Fassen wir unsere Erkenntnis zusammen und lassen die LED pulsieren:</p>
<div id="f26baf19" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1"></a><span class="im">import</span> time</span>
<span id="cb11-2"><a href="#cb11-2"></a></span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="co"># Increase red step by step</span></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb11-5"><a href="#cb11-5"></a>    led.set_rgb_value(r, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb11-6"><a href="#cb11-6"></a>    time.sleep(<span class="fl">0.001</span>)</span>
<span id="cb11-7"><a href="#cb11-7"></a></span>
<span id="cb11-8"><a href="#cb11-8"></a><span class="co"># Stay at full brightness for a bit</span></span>
<span id="cb11-9"><a href="#cb11-9"></a>time.sleep(<span class="fl">0.25</span>)</span>
<span id="cb11-10"><a href="#cb11-10"></a></span>
<span id="cb11-11"><a href="#cb11-11"></a><span class="co"># Decrease red step by step</span></span>
<span id="cb11-12"><a href="#cb11-12"></a><span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb11-13"><a href="#cb11-13"></a>    led.set_rgb_value(r, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb11-14"><a href="#cb11-14"></a>    time.sleep(<span class="fl">0.001</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Soweit bekannt? Fast, eine kleine Neuerung habe ich gerade eingebaut, nämlich mit der Funktion <code>time.sleep()</code>. Diese Funktion pausiert das Programm für die angegebene Zeit in Sekunden. In unserem Fall pausieren wir für 0,001 Sekunden, also 1 Millisekunde. Dadurch wird die LED langsamer heller und dunkler, was den Pulsationseffekt verstärkt. Ohne diese Pause würde die LED so schnell aufleuchten, dass es für das menschliche Auge nicht mehr wahrnehmbar wäre. Tatsächlich würden wir auch die Hardware überfordern, weil die LED gar nicht so schnell die Farbe wechseln kann. Das Programm würde abstürzen.</p>
<p>Auf dem Höhepunkt warten wir erneut, dieses Mal eine Viertelsekunde, bevor wir die LED langsam ausgehen lassen und den Rotanteil schrittweise wieder auf Null setzen. Dann endet unser Programm, leider viel zu früh. Die LED soll doch eigentlich weiter pulsieren, bis… ja bis wann überhaupt?</p>
</section>
<section id="bedingte-wiederholungen" class="level3" data-number="1.6.2">
<h3 data-number="1.6.2" class="anchored" data-anchor-id="bedingte-wiederholungen"><span class="header-section-number">1.6.2</span> Bedingte Wiederholungen</h3>
<p>Beim Lösen von Problemen stoßen wir häufig auf Situationen, in denen wir bestimmte Schritte wiederholt ausführen möchten, aber nur unter bestimmten Bedingungen. Hier kommen bedingte Wiederholungen ins Spiel, die es uns ermöglichen, Schleifen zu erstellen, die nur dann fortgesetzt werden, wenn eine bestimmte Bedingung noch erfüllt ist.</p>
<p>Das können wir auf unsere pulsierende LED anwenden. Sie soll ihren Pulsierzyklus Dunkel-Hell-Dunkel wiederholen, solange der Benutzer nicht unterbricht. Das ist zumindest ein pragmatisches Abbruchkriterium für unseren Fall. Wir definieren also hier keine feste Anzahl Wiederholungen, wie bei der <code>for ... in</code>-Schleife, sondern wir wollen festlegen, unter welcher <em>Bedingung</em> die Schleife fortgesetzt wird. Wir könnten also sagen: <em>solange</em> die Bedingung X erfüllt ist, wiederhole die aufgeführten Schritte. Und weil Programmiersprachen für Menschen gemacht sind, klingt es im echten Programm auch so ähnlich:</p>
<div id="a0dbd6e4" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1"></a><span class="cf">while</span> <span class="dv">1</span><span class="op">==</span><span class="dv">1</span>:</span>
<span id="cb12-2"><a href="#cb12-2"></a>    <span class="bu">print</span>(<span class="st">"The condition is always true"</span>)</span>
<span id="cb12-3"><a href="#cb12-3"></a>    time.sleep(<span class="dv">1</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Das Schlüsselwort <code>while</code> führt eine bedingte Schleife ein, gefolgt von der Bedingung, die die Schleife steuert. Die Bedingung wird vor jedem neuen Schleifendurchlauf geprüft (auch vor dem ersten) und sollte sie falsch (<code>false</code>) sein, wird die Schleife beendet.</p>
<p>Wann wird die Schleife oben also beendet? Richtig - niemals. Die Bedingung <code>1==1</code> ist immer wahr, die Schleife läuft somit endlos. Wir sprechen auch von einer Endlosschleife, die wir in der Programmierung unbedingt vermeiden wollen, es sei denn, sie ist explizit gewollt und nicht versehentlich entstanden. Das kurze Programm oben schreibt also in Abständen von einer Sekunde den Text “The condition is always true” auf die Konsole.</p>
<p>Eine Bedingung ist in Python und anderen Programmiersprache ein wichtiges Konzept, das es uns ermöglicht, Entscheidungen zu treffen und den Programmfluss zu steuern. In unserem Fall könnte die Bedingung lauten: <em>solange der Benutzer nicht stoppt, wiederhole den Pulsierzyklus</em>. Eine Bedingung hat die Eigenschaft, dass sie jederzeit evaluiert werden kann und entweder den Wert wahr (true) oder falsch (false) annimmt. Wie aber drücken wir das in Python aus?</p>
<div id="8c0d7666" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1"></a><span class="im">import</span> keyboard</span>
<span id="cb13-2"><a href="#cb13-2"></a></span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="cf">while</span> <span class="kw">not</span> keyboard.is_pressed(<span class="st">'esc'</span>):</span>
<span id="cb13-4"><a href="#cb13-4"></a>    <span class="bu">print</span>(<span class="st">"Nobody pressed ESC yet"</span>)</span>
<span id="cb13-5"><a href="#cb13-5"></a>    time.sleep(<span class="dv">1</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Für Ereignisse, die die Tastatur betreffen, können wir uns der Bibliothek <code>keyboard</code> bedienen, die es uns ermöglicht, Tasteneingaben einfach zu überwachen. Der Ausdruck oder die Bedingung <code>not keyboard.is_pressed('esc')</code> prüft, ob die ESC-Taste gedrückt ist. Wegen des <code>not</code> wird die Schleife fortgesetzt, solange die ESC-Taste <em>nicht</em> gedrückt ist. Das Schlüsselwort verneint das Ergebnis einer Bedingung. Aus <code>True</code> wird <code>False</code>, und umgekehrt.</p>
<p>Die <a href="#bibliotheken">Bibliothek</a> <code>keyboard</code> ist eine so genannte externe Bibliothek und muss vor der Verwendung installiert werden. Das könnt ihr über den Paketmanager <code>pip</code> bewerkstelligen, der mit jeder Python-Installation mitgeliefert wird. Gebt auf der Kommandozeile dazu den folgenden Befehl ein:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1"></a><span class="ex">pip</span> install keyboard</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Anschließend ist die Bibliothek in eurer Python-Umgebung vorhanden und sollte mit dem <code>import</code>-Befehl erfolgreich geladen werden können.</p>
<p>Wenn wir jetzt unseren für einen Pulsierzyklus von Oben in die neue bedingte Schleife einfügen, sind wir schon am Ziel. Der Pulsierzyklus wird wiederholt, solange der Benutzer nicht die Taste Escape drückt.</p>
<div id="56b06860" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1"></a><span class="im">import</span> keyboard</span>
<span id="cb15-2"><a href="#cb15-2"></a></span>
<span id="cb15-3"><a href="#cb15-3"></a><span class="cf">while</span> <span class="kw">not</span> keyboard.is_pressed(<span class="st">'esc'</span>):</span>
<span id="cb15-4"><a href="#cb15-4"></a></span>
<span id="cb15-5"><a href="#cb15-5"></a>    <span class="co"># Increase red step by step</span></span>
<span id="cb15-6"><a href="#cb15-6"></a>    <span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb15-7"><a href="#cb15-7"></a>        led.set_rgb_value(r, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb15-8"><a href="#cb15-8"></a>        time.sleep(<span class="fl">0.001</span>)</span>
<span id="cb15-9"><a href="#cb15-9"></a></span>
<span id="cb15-10"><a href="#cb15-10"></a>    <span class="co"># Stay at full brightness for a bit</span></span>
<span id="cb15-11"><a href="#cb15-11"></a>    time.sleep(<span class="fl">0.25</span>)</span>
<span id="cb15-12"><a href="#cb15-12"></a></span>
<span id="cb15-13"><a href="#cb15-13"></a>    <span class="co"># Decrease red step by step</span></span>
<span id="cb15-14"><a href="#cb15-14"></a>    <span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb15-15"><a href="#cb15-15"></a>        led.set_rgb_value(r, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb15-16"><a href="#cb15-16"></a>        time.sleep(<span class="fl">0.001</span>)</span>
<span id="cb15-17"><a href="#cb15-17"></a></span>
<span id="cb15-18"><a href="#cb15-18"></a>    <span class="co"># Stay at full dark for a bit</span></span>
<span id="cb15-19"><a href="#cb15-19"></a>    time.sleep(<span class="fl">0.25</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Für die Vollständigkeit das Ganze inklusive des <a href="#boilerplate-code">Boilerplate-Codes</a> für die Verbindung zu den Tinkerforge-Geräten:</p>
<div id="21b4e1b0" class="cell" data-execution_count="18">
<div id="lst-pulse-program" class="python cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-pulse-program-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Listing&nbsp;1.2: Das fertige Programm, das die LED rot pulsieren lässt.
</figcaption>
<div aria-describedby="lst-pulse-program-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1"></a><span class="im">import</span> time</span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="im">from</span> tinkerforge.ip_connection <span class="im">import</span> IPConnection</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="im">from</span> tinkerforge.bricklet_rgb_led_v2 <span class="im">import</span> BrickletRGBLEDV2</span>
<span id="cb16-4"><a href="#cb16-4"></a></span>
<span id="cb16-5"><a href="#cb16-5"></a>ipcon <span class="op">=</span> IPConnection()</span>
<span id="cb16-6"><a href="#cb16-6"></a>ipcon.<span class="ex">connect</span>(<span class="st">'localhost'</span>, <span class="dv">4223</span>) </span>
<span id="cb16-7"><a href="#cb16-7"></a>led <span class="op">=</span> BrickletRGBLEDV2(<span class="st">'ZEP'</span>, ipcon)</span>
<span id="cb16-8"><a href="#cb16-8"></a></span>
<span id="cb16-9"><a href="#cb16-9"></a><span class="co"># Turn LED off initially</span></span>
<span id="cb16-10"><a href="#cb16-10"></a>led.set_rgb_value(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb16-11"><a href="#cb16-11"></a></span>
<span id="cb16-12"><a href="#cb16-12"></a><span class="cf">while</span> <span class="kw">not</span> keyboard.is_pressed(<span class="st">'esc'</span>):</span>
<span id="cb16-13"><a href="#cb16-13"></a></span>
<span id="cb16-14"><a href="#cb16-14"></a>    <span class="co"># Increase red step by step</span></span>
<span id="cb16-15"><a href="#cb16-15"></a>    <span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb16-16"><a href="#cb16-16"></a>        led.set_rgb_value(r, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb16-17"><a href="#cb16-17"></a>        time.sleep(<span class="fl">0.001</span>)</span>
<span id="cb16-18"><a href="#cb16-18"></a></span>
<span id="cb16-19"><a href="#cb16-19"></a>    <span class="co"># Stay at full brightness for a bit</span></span>
<span id="cb16-20"><a href="#cb16-20"></a>    time.sleep(<span class="fl">0.25</span>)</span>
<span id="cb16-21"><a href="#cb16-21"></a></span>
<span id="cb16-22"><a href="#cb16-22"></a>    <span class="co"># Decrease red step by step</span></span>
<span id="cb16-23"><a href="#cb16-23"></a>    <span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb16-24"><a href="#cb16-24"></a>        led.set_rgb_value(r, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb16-25"><a href="#cb16-25"></a>        time.sleep(<span class="fl">0.001</span>)</span>
<span id="cb16-26"><a href="#cb16-26"></a></span>
<span id="cb16-27"><a href="#cb16-27"></a>    <span class="co"># Stay at full dark for a bit</span></span>
<span id="cb16-28"><a href="#cb16-28"></a>    time.sleep(<span class="fl">0.25</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="farbkreise" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="farbkreise"><span class="header-section-number">1.7</span> Farbkreise</h2>
<p>Das RGB-Farbschema ist für Computer optimal, weil sich damit mit nur drei Zahlen jede beliebige Farbe kodieren lässt. Zahlen sind schließlich die Sprache, mit der Computer am besten umgehen können. Für uns Menschen ist dieses Schema jedoch weniger intuitiv. Oder könntet ihr auf Anhieb sagen, welche Farbe hinter der Kombination (67, 201, 182) steckt?</p>
<p>Um Farben für uns leichter wählbar zu machen, wurde der sogenannte Hue-Farbkreis entwickelt. Er ordnet die Farben auf einer Skala von 0 bis 360 Grad an – ähnlich wie die Winkel auf einem Kreis. Neben dem Farbton (Hue) lassen sich zusätzlich die Sättigung und die Helligkeit einstellen: Der Farbton bestimmt die eigentliche Farbe, die Sättigung, wie kräftig oder blass sie wirkt, und die Helligkeit, wie hell oder dunkel sie erscheint.</p>
<div id="fig-hue-color-picker" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hue-color-picker-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/hue_color_picker.gif" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Abbildung&nbsp;1.8: Die Farbauswahl in Google Slides funktioniert über den Hue-Farbkreis."><img src="images/hue_color_picker.gif" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:33.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hue-color-picker-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1.8: Die Farbauswahl in Google Slides funktioniert über den Hue-Farbkreis.
</figcaption>
</figure>
</div>
<p>In <a href="#fig-hue-color-picker" class="quarto-xref">Abbildung&nbsp;<span>1.8</span></a> seht ihr, wie die Farbauswahl in Google Slides funktioniert. Mit dem Slider in der Mitte bestimmt ihr den Farbton. Habt ihr einen passenden Ton gefunden, könnt ihr im Rechteck darüber durch Verschieben des kleinen Kreises die Sättigung und Helligkeit anpassen.</p>
<p>Beobachtet ihr dabei die RGB-Werte, erkennt ihr die Systematik der Farbton-Skala: Ausgehend von reinem Rot wird Schritt für Schritt Grün hinzugefügt – so entstehen Orange und Gelb. Danach nimmt der Rotanteil ab, während Blau hinzukommt. Über Cyan gelangen wir zu reinem Blau. Schließlich wird wieder Rot beigemischt, wodurch Violett bis Pink entstehen. Auf diese Weise bildet der Kreis den gesamten Regenbogen ab.</p>
<p>Da die Skala am Ende wieder bei Rot ankommt, lässt sich der Farbverlauf nahtlos wiederholen – ohne harte Übergänge. Genau deshalb wird der Hue-Verlauf meist als Kreis dargestellt.</p>
<div id="fig-hue-color-circle" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hue-color-circle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/hue_color_circle_hsv.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Abbildung&nbsp;1.9: Der Hue-Farbkreis mit HSV-Werten."><img src="images/hue_color_circle_hsv.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hue-color-circle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1.9: Der Hue-Farbkreis mit HSV-Werten.
</figcaption>
</figure>
</div>
<p><a href="#fig-hue-color-circle" class="quarto-xref">Abbildung&nbsp;<span>1.9</span></a> zeigt den Hue-Farbkreis im HSV-Modell. HSV steht für Hue, Saturation, Value (Farbton, Sättigung, Helligkeit). Der Wert Value gibt die Helligkeit auf einer Skala von 0 bis 100 % an. Im Bild ist die Helligkeit konstant bei 100 %, während die Sättigung von innen nach außen zunimmt. In der Mitte sehen wir deshalb Weiß, während am äußeren Rand die Farben ihre volle Intensität haben.</p>
<p>Wenn wir ein Programm schreiben, das die gesamte Hue-Farbskala durchläuft und die LED jeweils in der passenden Farbe aufleuchten lässt, erhalten wir unser Regenbogenprogramm. Da die LED RGB-Werte benötigt, müssen wir den Verlauf des Hue-Farbkreises in RGB umsetzen. Ein Blick auf die Animation in <a href="#fig-hue-color-picker" class="quarto-xref">Abbildung&nbsp;<span>1.8</span></a> hilft: Der Farbverlauf lässt sich in sechs Phasen unterteilen, wie <a href="#fig-hue-rgb-diagram" class="quarto-xref">Abbildung&nbsp;<span>1.10</span></a> zeigt:</p>
<ol type="1">
<li>Rot = 255, Blau = 0, Grün steigt linear</li>
<li>Rot sinkt linear, Grün = 255, Blau = 0</li>
<li>Rot = 0, Grün = 255, Blau steigt linear</li>
<li>Rot = 0, Grün sinkt linear, Blau = 255</li>
<li>Rot steigt linear, Grün = 0, Blau = 255</li>
<li>Rot = 255, Grün = 0, Blau sinkt linear</li>
</ol>
<p>Dann beginnt der Zyklus von vorn.</p>
<div id="fig-hue-rgb-diagram" class="lightbox quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hue-rgb-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/hue_rgb_diagram.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Abbildung&nbsp;1.10: Der Hue-Farbverlauf mit den Veränderungen der RGB-Werte (Quelle: Ronja’s Tutorials)."><img src="images/hue_rgb_diagram.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hue-rgb-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1.10: Der Hue-Farbverlauf mit den Veränderungen der RGB-Werte (Quelle: <a href="https://www.ronja-tutorials.com/post/041-hsv-colorspace/">Ronja’s Tutorials</a>).
</figcaption>
</figure>
</div>
<section id="farbkreis-als-programm" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="farbkreis-als-programm"><span class="header-section-number">1.7.1</span> Farbkreis als Programm</h3>
<p>Beginnen wir mit der ersten Phase und schreiben dafür ein Python-Programm:</p>
<div id="89c439e2" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1"></a><span class="cf">for</span> green <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb17-2"><a href="#cb17-2"></a>    led.set_rgb_value(<span class="dv">255</span>, green, <span class="dv">0</span>)</span>
<span id="cb17-3"><a href="#cb17-3"></a>    time.sleep(<span class="fl">0.01</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Weil wir genau wissen, wie oft wir die Schleife durchlaufen wollen, verwenden wir eine <code>for</code>-Schleife. Innerhalb der Schleife erhöhen wir die Variable <code>green</code> jeweils um 1, was effektiv den Grünanteil unseres RGB-Wertes erhöht. Mit jedem Durchlauf fügen wir somit mehr Grün hinzu, während Rot und Blau konstant bleiben. Phase 1 ist damit abgeschlossen - machen wir weiter mit Phase 2:</p>
<div id="083e5ad0" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1"></a><span class="cf">for</span> red <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb18-2"><a href="#cb18-2"></a>    led.set_rgb_value(red, <span class="dv">255</span>, <span class="dv">0</span>)</span>
<span id="cb18-3"><a href="#cb18-3"></a>    time.sleep(<span class="fl">0.01</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wie wir mit einer <code>for</code>-Schleife rückwärts zählen, haben wir schon weiter oben kennengelernt. In Phase zwei verringern wir schrittweise den Rotanteil, während die anderen beiden Farben konstant bleiben. Damit kommen wir zu Phase 3:</p>
<div id="0332fb07" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1"></a><span class="cf">for</span> blue <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb19-2"><a href="#cb19-2"></a>    led.set_rgb_value(<span class="dv">0</span>, <span class="dv">255</span>, blue)</span>
<span id="cb19-3"><a href="#cb19-3"></a>    time.sleep(<span class="fl">0.01</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ich glaube, ihr habt das Prinzip verstanden. Indem wir die sechs Phasen jeweils in einer eigenen Schleife abarbeiten, erhalten wir das vollständige Regenbogenprogramm:</p>
<div id="0017f566" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># phase 1</span></span>
<span id="cb20-2"><a href="#cb20-2"></a><span class="cf">for</span> green <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb20-3"><a href="#cb20-3"></a>    led.set_rgb_value(<span class="dv">255</span>, green, <span class="dv">0</span>)</span>
<span id="cb20-4"><a href="#cb20-4"></a>    time.sleep(<span class="fl">0.01</span>)</span>
<span id="cb20-5"><a href="#cb20-5"></a></span>
<span id="cb20-6"><a href="#cb20-6"></a><span class="co"># phase 2</span></span>
<span id="cb20-7"><a href="#cb20-7"></a><span class="cf">for</span> red <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb20-8"><a href="#cb20-8"></a>    led.set_rgb_value(red, <span class="dv">255</span>, <span class="dv">0</span>)</span>
<span id="cb20-9"><a href="#cb20-9"></a>    time.sleep(<span class="fl">0.01</span>)</span>
<span id="cb20-10"><a href="#cb20-10"></a></span>
<span id="cb20-11"><a href="#cb20-11"></a><span class="co"># phase 3</span></span>
<span id="cb20-12"><a href="#cb20-12"></a><span class="cf">for</span> blue <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb20-13"><a href="#cb20-13"></a>    led.set_rgb_value(<span class="dv">0</span>, <span class="dv">255</span>, blue)</span>
<span id="cb20-14"><a href="#cb20-14"></a>    time.sleep(<span class="fl">0.01</span>)</span>
<span id="cb20-15"><a href="#cb20-15"></a></span>
<span id="cb20-16"><a href="#cb20-16"></a><span class="co"># phase 4</span></span>
<span id="cb20-17"><a href="#cb20-17"></a><span class="cf">for</span> green <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb20-18"><a href="#cb20-18"></a>    led.set_rgb_value(<span class="dv">0</span>, green, <span class="dv">255</span>)</span>
<span id="cb20-19"><a href="#cb20-19"></a>    time.sleep(<span class="fl">0.01</span>)</span>
<span id="cb20-20"><a href="#cb20-20"></a></span>
<span id="cb20-21"><a href="#cb20-21"></a><span class="co"># phase 5</span></span>
<span id="cb20-22"><a href="#cb20-22"></a><span class="cf">for</span> red <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb20-23"><a href="#cb20-23"></a>    led.set_rgb_value(red, <span class="dv">0</span>, <span class="dv">255</span>)</span>
<span id="cb20-24"><a href="#cb20-24"></a>    time.sleep(<span class="fl">0.01</span>)</span>
<span id="cb20-25"><a href="#cb20-25"></a></span>
<span id="cb20-26"><a href="#cb20-26"></a><span class="co"># phase 6</span></span>
<span id="cb20-27"><a href="#cb20-27"></a><span class="cf">for</span> blue <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb20-28"><a href="#cb20-28"></a>    led.set_rgb_value(<span class="dv">255</span>, <span class="dv">0</span>, blue)</span>
<span id="cb20-29"><a href="#cb20-29"></a>    time.sleep(<span class="fl">0.01</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wie schön 🌈 Eine Sache fehlt aber noch.</p>
</section>
<section id="der-zyklus-wiederholt-sich" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="der-zyklus-wiederholt-sich"><span class="header-section-number">1.7.2</span> Der Zyklus wiederholt sich</h3>
<p>Der Regenbogen soll am Ende wieder von Vorne beginnen. Wie schon beim Pulsieren der Farben können wir auch hier eine <code>while</code>-Schleife verwenden und die Phasen kontinuierlich abspielen. Solange bis der Benutzer die Escape-Taste drückt:</p>
<div id="0ed93ccc" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1"></a><span class="cf">while</span> <span class="kw">not</span> keyboard.is_pressed(<span class="st">'esc'</span>):</span>
<span id="cb21-2"><a href="#cb21-2"></a></span>
<span id="cb21-3"><a href="#cb21-3"></a>    <span class="co"># phase 1</span></span>
<span id="cb21-4"><a href="#cb21-4"></a>    <span class="cf">for</span> green <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb21-5"><a href="#cb21-5"></a>        led.set_rgb_value(<span class="dv">255</span>, green, <span class="dv">0</span>)</span>
<span id="cb21-6"><a href="#cb21-6"></a>        time.sleep(<span class="fl">0.01</span>)</span>
<span id="cb21-7"><a href="#cb21-7"></a></span>
<span id="cb21-8"><a href="#cb21-8"></a>    <span class="co"># phase 2</span></span>
<span id="cb21-9"><a href="#cb21-9"></a>    <span class="cf">for</span> red <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb21-10"><a href="#cb21-10"></a>        led.set_rgb_value(red, <span class="dv">255</span>, <span class="dv">0</span>)</span>
<span id="cb21-11"><a href="#cb21-11"></a>        time.sleep(<span class="fl">0.01</span>)</span>
<span id="cb21-12"><a href="#cb21-12"></a></span>
<span id="cb21-13"><a href="#cb21-13"></a>    <span class="co"># phase 3</span></span>
<span id="cb21-14"><a href="#cb21-14"></a>    <span class="cf">for</span> blue <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb21-15"><a href="#cb21-15"></a>        led.set_rgb_value(<span class="dv">0</span>, <span class="dv">255</span>, blue)</span>
<span id="cb21-16"><a href="#cb21-16"></a>        time.sleep(<span class="fl">0.01</span>)</span>
<span id="cb21-17"><a href="#cb21-17"></a></span>
<span id="cb21-18"><a href="#cb21-18"></a>    <span class="co"># phase 4</span></span>
<span id="cb21-19"><a href="#cb21-19"></a>    <span class="cf">for</span> green <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb21-20"><a href="#cb21-20"></a>        led.set_rgb_value(<span class="dv">0</span>, green, <span class="dv">255</span>)</span>
<span id="cb21-21"><a href="#cb21-21"></a>        time.sleep(<span class="fl">0.01</span>)</span>
<span id="cb21-22"><a href="#cb21-22"></a></span>
<span id="cb21-23"><a href="#cb21-23"></a>    <span class="co"># phase 5</span></span>
<span id="cb21-24"><a href="#cb21-24"></a>    <span class="cf">for</span> red <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb21-25"><a href="#cb21-25"></a>        led.set_rgb_value(red, <span class="dv">0</span>, <span class="dv">255</span>)</span>
<span id="cb21-26"><a href="#cb21-26"></a>        time.sleep(<span class="fl">0.01</span>)</span>
<span id="cb21-27"><a href="#cb21-27"></a></span>
<span id="cb21-28"><a href="#cb21-28"></a>    <span class="co"># phase 6</span></span>
<span id="cb21-29"><a href="#cb21-29"></a>    <span class="cf">for</span> blue <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb21-30"><a href="#cb21-30"></a>        led.set_rgb_value(<span class="dv">255</span>, <span class="dv">0</span>, blue)</span>
<span id="cb21-31"><a href="#cb21-31"></a>        time.sleep(<span class="fl">0.01</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir haben es fast geschafft! Eine Kleinigkeit wollen wir an unserem Programm noch verbessern.</p>
</section>
<section id="zeitsteuerung" class="level3" data-number="1.7.3">
<h3 data-number="1.7.3" class="anchored" data-anchor-id="zeitsteuerung"><span class="header-section-number">1.7.3</span> Zeitsteuerung</h3>
<p>Vielleicht habt ihr gemerkt, dass die Geschwindigkeit, mit der unsere LED den gesamten Regenbogen einmal durchläuft, nicht sehr hoch ist. Ich würde das gerne beschleunigen. Die Zeit steuern wir über die <code>time.sleep()</code>-Funktion, sodass wir einfach den Wert in jedem Funktionsaufruf verringern könnten. Das wäre aber nicht sehr effizient, weil wir ihn an sechs Stellen anpassen müssen. Wenn wir danach merken, dass es zu schnell ist, müsstem wir den Wert erneut überall editieren. Das geht einfacher!</p>
<p>Der Trick liegt darin, den Wert für die Wartedauer als Variable zu definieren und nur einer an einer Stelle zu ändern.</p>
<div id="84995d3c" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1"></a>pause_duration <span class="op">=</span> <span class="fl">0.01</span></span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="cf">while</span> <span class="kw">not</span> keyboard.is_pressed(<span class="st">'esc'</span>):</span>
<span id="cb22-3"><a href="#cb22-3"></a></span>
<span id="cb22-4"><a href="#cb22-4"></a>    <span class="co"># phase 1</span></span>
<span id="cb22-5"><a href="#cb22-5"></a>    <span class="cf">for</span> green <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb22-6"><a href="#cb22-6"></a>        led.set_rgb_value(<span class="dv">255</span>, green, <span class="dv">0</span>)</span>
<span id="cb22-7"><a href="#cb22-7"></a>        time.sleep(pause_duration)</span>
<span id="cb22-8"><a href="#cb22-8"></a></span>
<span id="cb22-9"><a href="#cb22-9"></a>    <span class="co"># etc.</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Schon besser! Wir gehen aber noch einen Schritt weiter. Statt dieses kleinteiligen Wertes einer Pause zwischen einer kleinen Farbveränderung, möchte ich gerne die Gesamtdauer für den Durchlauf eine Regenbogens angeben. Der Wert <code>pause_duration</code> soll dann auf dieser Basis errechnet werden. Dazu müssen wir nur die Anzahl der Pausen ingesamt kennen, was in jeder der sechs Phasen 256 sind. Macht also:</p>
<p><span class="math display">\[
6 \times 256 = 1536
\]</span></p>
<p>In unserem Programm teilen wir also die Gesamtdauer in Sekunden geteilt durch 1536:</p>
<div id="30c3a85e" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1"></a>rainbow_duration <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb23-2"><a href="#cb23-2"></a>pause_duration <span class="op">=</span> rainbow_duration <span class="op">/</span> <span class="dv">1536</span></span>
<span id="cb23-3"><a href="#cb23-3"></a></span>
<span id="cb23-4"><a href="#cb23-4"></a><span class="cf">while</span> <span class="kw">not</span> keyboard.is_pressed(<span class="st">'esc'</span>):</span>
<span id="cb23-5"><a href="#cb23-5"></a></span>
<span id="cb23-6"><a href="#cb23-6"></a>    <span class="co"># phase 1</span></span>
<span id="cb23-7"><a href="#cb23-7"></a>    <span class="cf">for</span> green <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb23-8"><a href="#cb23-8"></a>        led.set_rgb_value(<span class="dv">255</span>, green, <span class="dv">0</span>)</span>
<span id="cb23-9"><a href="#cb23-9"></a>        time.sleep(pause_duration)</span>
<span id="cb23-10"><a href="#cb23-10"></a></span>
<span id="cb23-11"><a href="#cb23-11"></a>    <span class="co"># etc.</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Und schon können wir unseren Regenbogen beliebig zeitlich steuern. Damit sind wir am Ende des Kapitels angekommen. Wir schließen wir es mit dem vollständigen Code für unseren Regenbogenverlauf ab. Vergesst nicht den Wert für die UID eurer LED anzupassen, damit es auch bei euch funktioniert:</p>
<div id="6d14e0a9" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1"></a><span class="im">import</span> keyboard</span>
<span id="cb24-2"><a href="#cb24-2"></a><span class="im">import</span> time</span>
<span id="cb24-3"><a href="#cb24-3"></a><span class="im">from</span> tinkerforge.ip_connection <span class="im">import</span> IPConnection</span>
<span id="cb24-4"><a href="#cb24-4"></a><span class="im">from</span> tinkerforge.bricklet_rgb_led_v2 <span class="im">import</span> BrickletRGBLEDV2</span>
<span id="cb24-5"><a href="#cb24-5"></a></span>
<span id="cb24-6"><a href="#cb24-6"></a>ipcon <span class="op">=</span> IPConnection()</span>
<span id="cb24-7"><a href="#cb24-7"></a>ipcon.<span class="ex">connect</span>(<span class="st">'localhost'</span>, <span class="dv">4223</span>) </span>
<span id="cb24-8"><a href="#cb24-8"></a>led <span class="op">=</span> BrickletRGBLEDV2(<span class="st">'ZEP'</span>, ipcon)</span>
<span id="cb24-9"><a href="#cb24-9"></a></span>
<span id="cb24-10"><a href="#cb24-10"></a><span class="co"># Turn LED off initially</span></span>
<span id="cb24-11"><a href="#cb24-11"></a>led.set_rgb_value(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb24-12"><a href="#cb24-12"></a></span>
<span id="cb24-13"><a href="#cb24-13"></a>rainbow_duration <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb24-14"><a href="#cb24-14"></a>pause_duration <span class="op">=</span> rainbow_duration <span class="op">/</span> <span class="dv">1536</span></span>
<span id="cb24-15"><a href="#cb24-15"></a></span>
<span id="cb24-16"><a href="#cb24-16"></a><span class="co"># Loop until user presses escape key</span></span>
<span id="cb24-17"><a href="#cb24-17"></a><span class="cf">while</span> <span class="kw">not</span> keyboard.is_pressed(<span class="st">'esc'</span>):</span>
<span id="cb24-18"><a href="#cb24-18"></a></span>
<span id="cb24-19"><a href="#cb24-19"></a>    <span class="co"># phase 1</span></span>
<span id="cb24-20"><a href="#cb24-20"></a>    <span class="cf">for</span> green <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb24-21"><a href="#cb24-21"></a>        led.set_rgb_value(<span class="dv">255</span>, green, <span class="dv">0</span>)</span>
<span id="cb24-22"><a href="#cb24-22"></a>        time.sleep(pause_duration)</span>
<span id="cb24-23"><a href="#cb24-23"></a></span>
<span id="cb24-24"><a href="#cb24-24"></a>    <span class="co"># phase 2</span></span>
<span id="cb24-25"><a href="#cb24-25"></a>    <span class="cf">for</span> red <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb24-26"><a href="#cb24-26"></a>        led.set_rgb_value(red, <span class="dv">255</span>, <span class="dv">0</span>)</span>
<span id="cb24-27"><a href="#cb24-27"></a>        time.sleep(pause_duration)</span>
<span id="cb24-28"><a href="#cb24-28"></a></span>
<span id="cb24-29"><a href="#cb24-29"></a>    <span class="co"># phase 3</span></span>
<span id="cb24-30"><a href="#cb24-30"></a>    <span class="cf">for</span> blue <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb24-31"><a href="#cb24-31"></a>        led.set_rgb_value(<span class="dv">0</span>, <span class="dv">255</span>, blue)</span>
<span id="cb24-32"><a href="#cb24-32"></a>        time.sleep(pause_duration)</span>
<span id="cb24-33"><a href="#cb24-33"></a></span>
<span id="cb24-34"><a href="#cb24-34"></a>    <span class="co"># phase 4</span></span>
<span id="cb24-35"><a href="#cb24-35"></a>    <span class="cf">for</span> green <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb24-36"><a href="#cb24-36"></a>        led.set_rgb_value(<span class="dv">0</span>, green, <span class="dv">255</span>)</span>
<span id="cb24-37"><a href="#cb24-37"></a>        time.sleep(pause_duration)</span>
<span id="cb24-38"><a href="#cb24-38"></a></span>
<span id="cb24-39"><a href="#cb24-39"></a>    <span class="co"># phase 5</span></span>
<span id="cb24-40"><a href="#cb24-40"></a>    <span class="cf">for</span> red <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">256</span>):</span>
<span id="cb24-41"><a href="#cb24-41"></a>        led.set_rgb_value(red, <span class="dv">0</span>, <span class="dv">255</span>)</span>
<span id="cb24-42"><a href="#cb24-42"></a>        time.sleep(pause_duration)</span>
<span id="cb24-43"><a href="#cb24-43"></a></span>
<span id="cb24-44"><a href="#cb24-44"></a>    <span class="co"># phase 6</span></span>
<span id="cb24-45"><a href="#cb24-45"></a>    <span class="cf">for</span> blue <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">255</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb24-46"><a href="#cb24-46"></a>        led.set_rgb_value(<span class="dv">255</span>, <span class="dv">0</span>, blue)</span>
<span id="cb24-47"><a href="#cb24-47"></a>        time.sleep(pause_duration)</span>
<span id="cb24-48"><a href="#cb24-48"></a></span>
<span id="cb24-49"><a href="#cb24-49"></a><span class="co"># Turn LED off</span></span>
<span id="cb24-50"><a href="#cb24-50"></a>led.set_rgb_value(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Seid ihr bereit für das nächste Experiment?</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-adami_what_2016" class="csl-entry" role="listitem">
Adami, Christoph. 2016. <span>„What is <span>Information</span>?“</span> <em>Philosophical Transactions of the Royal Society A: Mathematical, Physical and Engineering Sciences</em> 374 (2063): 20150230. <a href="https://doi.org/10.1098/rsta.2015.0230">https://doi.org/10.1098/rsta.2015.0230</a>.
</div>
<div id="ref-brookshear_computer_2020" class="csl-entry" role="listitem">
Brookshear, J. Glenn, und Dennis Brylow. 2020. <em>Computer science: an overview</em>. 13th edition, global edition. NY, NY: Pearson.
</div>
<div id="ref-petzold_code_2022" class="csl-entry" role="listitem">
Petzold, Charles. 2022. <em>Code: the hidden language of computer hardware and software</em>. 2. Aufl. Hoboken: Microsoft Press.
</div>
<div id="ref-polya" class="csl-entry" role="listitem">
Pólya, George, und John Horton Conway. 2004. <em>How to solve it: a new aspect of mathematical method</em>. Expanded Princeton Science Library ed. Princeton science library. Princeton [N.J.]: Princeton University Press.
</div>
<div id="ref-scott_but_2009" class="csl-entry" role="listitem">
Scott, John C. 2009. <em>But how do it know?: the basic principles of computers for everyone</em>. Oldsmar, FL: John C. Scott.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./prerequisites.html" class="pagination-link" aria-label="Voraussetzungen">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Voraussetzungen</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./numbers.html" class="pagination-link" aria-label="Zahlen 🔢">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Zahlen 🔢</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>